import { useState, useCallback } from 'react';
import { ScrollArea } from '@/components/ui/scroll-area';
import {
  Layout, Type, Square, Image, List, Table, FormInput,
  ToggleLeft, Sliders, Navigation, ChevronDown, ChevronRight,
  GripVertical, X, Search, Sparkles, ShoppingCart, Users,
  CreditCard, Lock, MessageSquare, BarChart3, Mail, Star,
  Columns, Globe, Shield, Zap, BookOpen, Bell, FileText,
} from 'lucide-react';
import { cn } from '@/lib/utils';
import { toast } from 'sonner';

interface ComponentTemplate {
  id: string;
  name: string;
  category: string;
  icon: typeof Layout;
  preview: string;
  code: string;
}

interface ComponentPaletteProps {
  open: boolean;
  onClose: () => void;
  onInsertComponent: (code: string, fileName?: string) => void;
}

const COMPONENTS: ComponentTemplate[] = [
  // ── Layout ──
  { id: 'hero', name: 'Hero Section', category: 'Layout', icon: Layout, preview: 'Full-width hero with heading, subtitle, and CTA',
    code: `<section class="relative py-24 px-6 bg-gradient-to-br from-slate-900 via-slate-800 to-slate-900 overflow-hidden">\n  <div class="absolute inset-0 bg-[radial-gradient(circle_at_30%_50%,rgba(56,189,248,0.08),transparent_50%)]"></div>\n  <div class="max-w-4xl mx-auto text-center relative z-10">\n    <h1 class="text-5xl md:text-6xl font-bold text-white tracking-tight mb-6">Build Something Amazing</h1>\n    <p class="text-lg text-slate-400 mb-10 max-w-2xl mx-auto">Create beautiful, responsive web applications with the power of AI-assisted development.</p>\n    <div class="flex items-center gap-4 justify-center">\n      <a href="#" class="px-8 py-3 bg-cyan-500 hover:bg-cyan-400 text-white font-semibold rounded-xl transition-colors shadow-lg shadow-cyan-500/20">Get Started</a>\n      <a href="#" class="px-8 py-3 border border-white/10 text-white/70 hover:text-white hover:border-white/20 rounded-xl transition-colors">Learn More</a>\n    </div>\n  </div>\n</section>` },
  { id: 'hero-split', name: 'Split Hero', category: 'Layout', icon: Columns, preview: 'Two-column hero with image and text',
    code: `<section class="py-20 px-6 bg-white">\n  <div class="max-w-6xl mx-auto grid md:grid-cols-2 gap-12 items-center">\n    <div>\n      <span class="text-sm font-semibold text-cyan-600 uppercase tracking-wider">Welcome</span>\n      <h1 class="text-4xl md:text-5xl font-bold text-slate-900 mt-3 mb-6">The Modern Way to Build Apps</h1>\n      <p class="text-lg text-slate-500 mb-8">Ship faster with AI-powered development tools. No compromises on quality.</p>\n      <div class="flex gap-3">\n        <a href="#" class="px-6 py-3 bg-slate-900 text-white rounded-xl font-medium hover:bg-slate-800 transition">Start Free</a>\n        <a href="#" class="px-6 py-3 border border-slate-200 text-slate-600 rounded-xl font-medium hover:bg-slate-50 transition">Watch Demo</a>\n      </div>\n    </div>\n    <div class="bg-gradient-to-br from-cyan-50 to-violet-50 rounded-2xl h-80 flex items-center justify-center">\n      <span class="text-slate-300 text-sm">Image / Illustration</span>\n    </div>\n  </div>\n</section>` },
  { id: 'features-grid', name: 'Features Grid', category: 'Layout', icon: Layout, preview: '3-column feature cards',
    code: `<section class="py-20 px-6 bg-white">\n  <div class="max-w-6xl mx-auto">\n    <h2 class="text-3xl font-bold text-center text-slate-900 mb-4">Features</h2>\n    <p class="text-center text-slate-500 mb-12 max-w-2xl mx-auto">Everything you need to build world-class applications.</p>\n    <div class="grid md:grid-cols-3 gap-8">\n      <div class="p-6 rounded-2xl border border-slate-200 hover:shadow-lg transition-shadow">\n        <div class="h-12 w-12 bg-cyan-50 rounded-xl flex items-center justify-center mb-4"><span class="text-2xl">⚡</span></div>\n        <h3 class="font-semibold text-slate-900 mb-2">Lightning Fast</h3>\n        <p class="text-sm text-slate-500">Optimized for speed and performance out of the box.</p>\n      </div>\n      <div class="p-6 rounded-2xl border border-slate-200 hover:shadow-lg transition-shadow">\n        <div class="h-12 w-12 bg-violet-50 rounded-xl flex items-center justify-center mb-4"><span class="text-2xl">🎨</span></div>\n        <h3 class="font-semibold text-slate-900 mb-2">Beautiful Design</h3>\n        <p class="text-sm text-slate-500">Pixel-perfect components crafted with attention to detail.</p>\n      </div>\n      <div class="p-6 rounded-2xl border border-slate-200 hover:shadow-lg transition-shadow">\n        <div class="h-12 w-12 bg-emerald-50 rounded-xl flex items-center justify-center mb-4"><span class="text-2xl">🔒</span></div>\n        <h3 class="font-semibold text-slate-900 mb-2">Secure by Default</h3>\n        <p class="text-sm text-slate-500">Enterprise-grade security built into every layer.</p>\n      </div>\n    </div>\n  </div>\n</section>` },
  { id: 'stats-section', name: 'Stats Section', category: 'Layout', icon: BarChart3, preview: '4 big number stats with labels',
    code: `<section class="py-16 px-6 bg-slate-900">\n  <div class="max-w-5xl mx-auto grid grid-cols-2 md:grid-cols-4 gap-8 text-center">\n    <div><div class="text-4xl font-bold text-white mb-1">10K+</div><div class="text-sm text-slate-400">Active Users</div></div>\n    <div><div class="text-4xl font-bold text-white mb-1">99.9%</div><div class="text-sm text-slate-400">Uptime</div></div>\n    <div><div class="text-4xl font-bold text-white mb-1">50M+</div><div class="text-sm text-slate-400">API Calls</div></div>\n    <div><div class="text-4xl font-bold text-white mb-1">150+</div><div class="text-sm text-slate-400">Countries</div></div>\n  </div>\n</section>` },
  { id: 'cta-banner', name: 'CTA Banner', category: 'Layout', icon: Zap, preview: 'Full-width call-to-action section',
    code: `<section class="py-20 px-6 bg-gradient-to-r from-cyan-600 to-violet-600">\n  <div class="max-w-3xl mx-auto text-center">\n    <h2 class="text-3xl md:text-4xl font-bold text-white mb-4">Ready to Get Started?</h2>\n    <p class="text-lg text-white/80 mb-8">Join thousands of developers building with our platform.</p>\n    <div class="flex gap-3 justify-center">\n      <a href="#" class="px-8 py-3 bg-white text-slate-900 font-semibold rounded-xl hover:bg-slate-100 transition shadow-lg">Start Free Trial</a>\n      <a href="#" class="px-8 py-3 border border-white/30 text-white font-medium rounded-xl hover:bg-white/10 transition">Talk to Sales</a>\n    </div>\n  </div>\n</section>` },

  // ── Content ──
  { id: 'pricing-table', name: 'Pricing Table', category: 'Content', icon: CreditCard, preview: '3-tier pricing comparison',
    code: `<section class="py-20 px-6 bg-slate-50">\n  <div class="max-w-5xl mx-auto">\n    <h2 class="text-3xl font-bold text-center text-slate-900 mb-12">Simple Pricing</h2>\n    <div class="grid md:grid-cols-3 gap-6">\n      <div class="bg-white rounded-2xl border border-slate-200 p-8">\n        <h3 class="text-lg font-semibold text-slate-900">Starter</h3>\n        <div class="mt-4 mb-6"><span class="text-4xl font-bold text-slate-900">$9</span><span class="text-slate-500">/mo</span></div>\n        <ul class="space-y-3 text-sm text-slate-600 mb-8"><li class="flex items-center gap-2"><span class="text-emerald-500">✓</span> 5 projects</li><li class="flex items-center gap-2"><span class="text-emerald-500">✓</span> Basic analytics</li><li class="flex items-center gap-2"><span class="text-emerald-500">✓</span> Email support</li></ul>\n        <button class="w-full py-2.5 rounded-xl border border-slate-200 text-sm font-medium text-slate-700 hover:bg-slate-50 transition">Get Started</button>\n      </div>\n      <div class="bg-slate-900 rounded-2xl p-8 text-white shadow-xl ring-2 ring-cyan-400/30">\n        <h3 class="text-lg font-semibold">Pro</h3>\n        <div class="mt-4 mb-6"><span class="text-4xl font-bold">$29</span><span class="text-slate-400">/mo</span></div>\n        <ul class="space-y-3 text-sm text-slate-300 mb-8"><li class="flex items-center gap-2"><span class="text-cyan-400">✓</span> Unlimited projects</li><li class="flex items-center gap-2"><span class="text-cyan-400">✓</span> Advanced analytics</li><li class="flex items-center gap-2"><span class="text-cyan-400">✓</span> Priority support</li></ul>\n        <button class="w-full py-2.5 rounded-xl bg-cyan-500 hover:bg-cyan-400 text-sm font-semibold transition">Get Started</button>\n      </div>\n      <div class="bg-white rounded-2xl border border-slate-200 p-8">\n        <h3 class="text-lg font-semibold text-slate-900">Enterprise</h3>\n        <div class="mt-4 mb-6"><span class="text-4xl font-bold text-slate-900">$99</span><span class="text-slate-500">/mo</span></div>\n        <ul class="space-y-3 text-sm text-slate-600 mb-8"><li class="flex items-center gap-2"><span class="text-emerald-500">✓</span> Everything in Pro</li><li class="flex items-center gap-2"><span class="text-emerald-500">✓</span> SSO & SAML</li><li class="flex items-center gap-2"><span class="text-emerald-500">✓</span> Dedicated support</li></ul>\n        <button class="w-full py-2.5 rounded-xl border border-slate-200 text-sm font-medium text-slate-700 hover:bg-slate-50 transition">Contact Sales</button>\n      </div>\n    </div>\n  </div>\n</section>` },
  { id: 'testimonials', name: 'Testimonials', category: 'Content', icon: MessageSquare, preview: 'Customer testimonials grid',
    code: `<section class="py-20 px-6 bg-slate-50">\n  <div class="max-w-4xl mx-auto">\n    <h2 class="text-3xl font-bold text-center text-slate-900 mb-12">What People Say</h2>\n    <div class="grid md:grid-cols-2 gap-6">\n      <div class="bg-white rounded-2xl p-6 border border-slate-200">\n        <div class="flex mb-3">★★★★★</div>\n        <p class="text-slate-600 text-sm mb-4">"This is the best tool I've ever used. It completely transformed how we build products."</p>\n        <div class="flex items-center gap-3"><div class="h-10 w-10 rounded-full bg-gradient-to-br from-cyan-400 to-blue-500 flex items-center justify-center text-white font-bold text-sm">AK</div><div><div class="text-sm font-semibold text-slate-900">Alex Kim</div><div class="text-xs text-slate-500">CEO, TechCorp</div></div></div>\n      </div>\n      <div class="bg-white rounded-2xl p-6 border border-slate-200">\n        <div class="flex mb-3">★★★★★</div>\n        <p class="text-slate-600 text-sm mb-4">"Incredible speed and quality. We shipped our MVP in under a week."</p>\n        <div class="flex items-center gap-3"><div class="h-10 w-10 rounded-full bg-gradient-to-br from-violet-400 to-pink-500 flex items-center justify-center text-white font-bold text-sm">SR</div><div><div class="text-sm font-semibold text-slate-900">Sarah Reyes</div><div class="text-xs text-slate-500">Founder, StartupXYZ</div></div></div>\n      </div>\n    </div>\n  </div>\n</section>` },
  { id: 'faq-accordion', name: 'FAQ Section', category: 'Content', icon: BookOpen, preview: 'Expandable FAQ with toggle',
    code: `<section class="py-20 px-6 bg-white">\n  <div class="max-w-3xl mx-auto">\n    <h2 class="text-3xl font-bold text-center text-slate-900 mb-12">Frequently Asked Questions</h2>\n    <div class="space-y-3">\n      <details class="group border border-slate-200 rounded-xl">\n        <summary class="flex items-center justify-between px-6 py-4 cursor-pointer text-sm font-medium text-slate-900">How does it work? <span class="text-slate-400 group-open:rotate-180 transition-transform">▼</span></summary>\n        <div class="px-6 pb-4 text-sm text-slate-500">Simply describe what you want to build and our AI will generate the code for you. You can then customize and deploy it instantly.</div>\n      </details>\n      <details class="group border border-slate-200 rounded-xl">\n        <summary class="flex items-center justify-between px-6 py-4 cursor-pointer text-sm font-medium text-slate-900">Can I export my code? <span class="text-slate-400 group-open:rotate-180 transition-transform">▼</span></summary>\n        <div class="px-6 pb-4 text-sm text-slate-500">Yes! You can export your project as a full React application, Docker container, or raw ZIP file at any time.</div>\n      </details>\n      <details class="group border border-slate-200 rounded-xl">\n        <summary class="flex items-center justify-between px-6 py-4 cursor-pointer text-sm font-medium text-slate-900">Is there a free plan? <span class="text-slate-400 group-open:rotate-180 transition-transform">▼</span></summary>\n        <div class="px-6 pb-4 text-sm text-slate-500">Yes, we offer a generous free tier with 5 projects and basic features to get you started.</div>\n      </details>\n    </div>\n  </div>\n</section>` },
  { id: 'blog-cards', name: 'Blog Cards', category: 'Content', icon: FileText, preview: '3-column blog post cards',
    code: `<section class="py-20 px-6 bg-white">\n  <div class="max-w-6xl mx-auto">\n    <h2 class="text-3xl font-bold text-slate-900 mb-8">Latest Posts</h2>\n    <div class="grid md:grid-cols-3 gap-6">\n      <article class="border border-slate-200 rounded-2xl overflow-hidden hover:shadow-lg transition">\n        <div class="h-48 bg-gradient-to-br from-cyan-100 to-blue-100"></div>\n        <div class="p-5">\n          <span class="text-xs font-semibold text-cyan-600 uppercase">Tutorial</span>\n          <h3 class="font-semibold text-slate-900 mt-2 mb-2">Getting Started with AI Development</h3>\n          <p class="text-sm text-slate-500 mb-3">Learn the fundamentals of building with AI-assisted tools.</p>\n          <a href="#" class="text-sm font-medium text-cyan-600 hover:text-cyan-500">Read more →</a>\n        </div>\n      </article>\n      <article class="border border-slate-200 rounded-2xl overflow-hidden hover:shadow-lg transition">\n        <div class="h-48 bg-gradient-to-br from-violet-100 to-pink-100"></div>\n        <div class="p-5">\n          <span class="text-xs font-semibold text-violet-600 uppercase">Guide</span>\n          <h3 class="font-semibold text-slate-900 mt-2 mb-2">Deploying to Production</h3>\n          <p class="text-sm text-slate-500 mb-3">Step-by-step guide to ship your app with confidence.</p>\n          <a href="#" class="text-sm font-medium text-cyan-600 hover:text-cyan-500">Read more →</a>\n        </div>\n      </article>\n      <article class="border border-slate-200 rounded-2xl overflow-hidden hover:shadow-lg transition">\n        <div class="h-48 bg-gradient-to-br from-amber-100 to-orange-100"></div>\n        <div class="p-5">\n          <span class="text-xs font-semibold text-amber-600 uppercase">Case Study</span>\n          <h3 class="font-semibold text-slate-900 mt-2 mb-2">How TechCorp Scaled 10x</h3>\n          <p class="text-sm text-slate-500 mb-3">Real results from a real team using our platform.</p>\n          <a href="#" class="text-sm font-medium text-cyan-600 hover:text-cyan-500">Read more →</a>\n        </div>\n      </article>\n    </div>\n  </div>\n</section>` },
  { id: 'newsletter', name: 'Newsletter Signup', category: 'Content', icon: Mail, preview: 'Email capture with inline form',
    code: `<section class="py-16 px-6 bg-slate-50">\n  <div class="max-w-xl mx-auto text-center">\n    <h2 class="text-2xl font-bold text-slate-900 mb-3">Stay in the Loop</h2>\n    <p class="text-slate-500 mb-6">Get the latest updates and tips delivered to your inbox.</p>\n    <form class="flex gap-2" onsubmit="event.preventDefault(); alert('Subscribed!')">\n      <input type="email" placeholder="your@email.com" class="flex-1 px-4 py-3 rounded-xl border border-slate-200 text-sm focus:ring-2 focus:ring-cyan-500/20 focus:border-cyan-500 outline-none" />\n      <button type="submit" class="px-6 py-3 bg-slate-900 text-white text-sm font-semibold rounded-xl hover:bg-slate-800 transition whitespace-nowrap">Subscribe</button>\n    </form>\n  </div>\n</section>` },

  // ── Forms ──
  { id: 'contact-form', name: 'Contact Form', category: 'Forms', icon: FormInput, preview: 'Name, email, message form',
    code: `<section class="py-20 px-6 bg-white">\n  <div class="max-w-lg mx-auto">\n    <h2 class="text-2xl font-bold text-slate-900 mb-2">Get in Touch</h2>\n    <p class="text-slate-500 mb-8">We'd love to hear from you.</p>\n    <form class="space-y-5" onsubmit="event.preventDefault(); alert('Form submitted!')">\n      <div class="grid grid-cols-2 gap-4">\n        <div><label class="text-sm font-medium text-slate-700 mb-1 block">First Name</label><input type="text" class="w-full px-4 py-2.5 rounded-xl border border-slate-200 text-sm focus:ring-2 focus:ring-cyan-500/20 focus:border-cyan-500 outline-none" placeholder="John"></div>\n        <div><label class="text-sm font-medium text-slate-700 mb-1 block">Last Name</label><input type="text" class="w-full px-4 py-2.5 rounded-xl border border-slate-200 text-sm focus:ring-2 focus:ring-cyan-500/20 focus:border-cyan-500 outline-none" placeholder="Doe"></div>\n      </div>\n      <div><label class="text-sm font-medium text-slate-700 mb-1 block">Email</label><input type="email" class="w-full px-4 py-2.5 rounded-xl border border-slate-200 text-sm focus:ring-2 focus:ring-cyan-500/20 focus:border-cyan-500 outline-none" placeholder="john@example.com"></div>\n      <div><label class="text-sm font-medium text-slate-700 mb-1 block">Message</label><textarea rows="4" class="w-full px-4 py-2.5 rounded-xl border border-slate-200 text-sm focus:ring-2 focus:ring-cyan-500/20 focus:border-cyan-500 outline-none resize-none" placeholder="Your message..."></textarea></div>\n      <button type="submit" class="w-full py-3 bg-slate-900 hover:bg-slate-800 text-white text-sm font-semibold rounded-xl transition-colors">Send Message</button>\n    </form>\n  </div>\n</section>` },
  { id: 'login-form', name: 'Login Form', category: 'Forms', icon: Lock, preview: 'Email/password login with social options',
    code: `<section class="min-h-screen flex items-center justify-center px-6 bg-slate-50">\n  <div class="w-full max-w-sm">\n    <div class="text-center mb-8"><h1 class="text-2xl font-bold text-slate-900">Welcome back</h1><p class="text-sm text-slate-500 mt-1">Sign in to your account</p></div>\n    <form class="space-y-4" onsubmit="event.preventDefault(); alert('Logged in!')">\n      <div><label class="text-sm font-medium text-slate-700 mb-1 block">Email</label><input type="email" class="w-full px-4 py-2.5 rounded-xl border border-slate-200 text-sm focus:ring-2 focus:ring-cyan-500/20 focus:border-cyan-500 outline-none" placeholder="you@example.com"></div>\n      <div><label class="text-sm font-medium text-slate-700 mb-1 block">Password</label><input type="password" class="w-full px-4 py-2.5 rounded-xl border border-slate-200 text-sm focus:ring-2 focus:ring-cyan-500/20 focus:border-cyan-500 outline-none" placeholder="••••••••"></div>\n      <div class="flex items-center justify-between text-sm"><label class="flex items-center gap-2 text-slate-600"><input type="checkbox" class="rounded"> Remember me</label><a href="#" class="text-cyan-600 hover:underline">Forgot password?</a></div>\n      <button type="submit" class="w-full py-3 bg-slate-900 hover:bg-slate-800 text-white text-sm font-semibold rounded-xl transition">Sign In</button>\n    </form>\n    <div class="mt-6 text-center text-sm text-slate-500">Don't have an account? <a href="#" class="text-cyan-600 hover:underline">Sign up</a></div>\n  </div>\n</section>` },
  { id: 'signup-form', name: 'Sign Up Form', category: 'Forms', icon: Users, preview: 'Registration form with validation',
    code: `<section class="min-h-screen flex items-center justify-center px-6 bg-white">\n  <div class="w-full max-w-sm">\n    <div class="text-center mb-8"><h1 class="text-2xl font-bold text-slate-900">Create Account</h1><p class="text-sm text-slate-500 mt-1">Start your free trial today</p></div>\n    <form class="space-y-4" onsubmit="event.preventDefault(); alert('Account created!')">\n      <div class="grid grid-cols-2 gap-3">\n        <div><label class="text-sm font-medium text-slate-700 mb-1 block">First</label><input type="text" class="w-full px-4 py-2.5 rounded-xl border border-slate-200 text-sm outline-none focus:ring-2 focus:ring-cyan-500/20" placeholder="Jane"></div>\n        <div><label class="text-sm font-medium text-slate-700 mb-1 block">Last</label><input type="text" class="w-full px-4 py-2.5 rounded-xl border border-slate-200 text-sm outline-none focus:ring-2 focus:ring-cyan-500/20" placeholder="Doe"></div>\n      </div>\n      <div><label class="text-sm font-medium text-slate-700 mb-1 block">Email</label><input type="email" class="w-full px-4 py-2.5 rounded-xl border border-slate-200 text-sm outline-none focus:ring-2 focus:ring-cyan-500/20" placeholder="you@example.com"></div>\n      <div><label class="text-sm font-medium text-slate-700 mb-1 block">Password</label><input type="password" class="w-full px-4 py-2.5 rounded-xl border border-slate-200 text-sm outline-none focus:ring-2 focus:ring-cyan-500/20" placeholder="Min 8 characters"></div>\n      <button type="submit" class="w-full py-3 bg-cyan-500 hover:bg-cyan-400 text-white text-sm font-semibold rounded-xl transition shadow-lg shadow-cyan-500/20">Create Account</button>\n    </form>\n    <p class="text-center text-xs text-slate-400 mt-6">By signing up, you agree to our <a href="#" class="underline">Terms</a> and <a href="#" class="underline">Privacy Policy</a>.</p>\n  </div>\n</section>` },

  // ── Navigation ──
  { id: 'navbar', name: 'Navigation Bar', category: 'Navigation', icon: Navigation, preview: 'Responsive navbar with logo and links',
    code: `<nav class="flex items-center justify-between px-6 py-4 bg-white border-b border-slate-100">\n  <a href="#" class="text-xl font-bold text-slate-900">Brand</a>\n  <div class="hidden md:flex items-center gap-8">\n    <a href="#" class="text-sm text-slate-600 hover:text-slate-900 transition">Features</a>\n    <a href="#" class="text-sm text-slate-600 hover:text-slate-900 transition">Pricing</a>\n    <a href="#" class="text-sm text-slate-600 hover:text-slate-900 transition">About</a>\n    <a href="#" class="px-5 py-2 bg-slate-900 text-white text-sm font-medium rounded-lg hover:bg-slate-800 transition">Sign Up</a>\n  </div>\n</nav>` },
  { id: 'navbar-dark', name: 'Dark Navbar', category: 'Navigation', icon: Navigation, preview: 'Dark themed navigation bar',
    code: `<nav class="flex items-center justify-between px-6 py-4 bg-slate-900 border-b border-white/5">\n  <a href="#" class="text-xl font-bold text-white">Brand</a>\n  <div class="hidden md:flex items-center gap-8">\n    <a href="#" class="text-sm text-slate-400 hover:text-white transition">Product</a>\n    <a href="#" class="text-sm text-slate-400 hover:text-white transition">Docs</a>\n    <a href="#" class="text-sm text-slate-400 hover:text-white transition">Pricing</a>\n    <a href="#" class="px-5 py-2 bg-cyan-500 text-white text-sm font-medium rounded-lg hover:bg-cyan-400 transition">Get Started</a>\n  </div>\n</nav>` },
  { id: 'sidebar-nav', name: 'Sidebar Nav', category: 'Navigation', icon: Layout, preview: 'Dashboard sidebar with icon links',
    code: `<aside class="w-64 h-screen bg-slate-900 border-r border-white/5 flex flex-col">\n  <div class="px-6 py-5 border-b border-white/5"><span class="text-lg font-bold text-white">Dashboard</span></div>\n  <nav class="flex-1 px-3 py-4 space-y-1">\n    <a href="#" class="flex items-center gap-3 px-3 py-2.5 rounded-lg bg-white/5 text-white text-sm font-medium">📊 Overview</a>\n    <a href="#" class="flex items-center gap-3 px-3 py-2.5 rounded-lg text-slate-400 hover:text-white hover:bg-white/5 text-sm transition">📦 Projects</a>\n    <a href="#" class="flex items-center gap-3 px-3 py-2.5 rounded-lg text-slate-400 hover:text-white hover:bg-white/5 text-sm transition">👥 Team</a>\n    <a href="#" class="flex items-center gap-3 px-3 py-2.5 rounded-lg text-slate-400 hover:text-white hover:bg-white/5 text-sm transition">⚙️ Settings</a>\n  </nav>\n  <div class="px-3 py-4 border-t border-white/5">\n    <a href="#" class="flex items-center gap-3 px-3 py-2.5 rounded-lg text-slate-400 hover:text-white hover:bg-white/5 text-sm transition">🚪 Logout</a>\n  </div>\n</aside>` },
  { id: 'footer', name: 'Footer', category: 'Navigation', icon: Layout, preview: 'Multi-column footer with links',
    code: `<footer class="bg-slate-900 text-white py-16 px-6">\n  <div class="max-w-6xl mx-auto grid md:grid-cols-4 gap-8">\n    <div><h3 class="font-bold text-lg mb-4">Brand</h3><p class="text-sm text-slate-400">Building the future of web development.</p></div>\n    <div><h4 class="font-semibold text-sm mb-3 text-slate-300">Product</h4><ul class="space-y-2 text-sm text-slate-400"><li><a href="#" class="hover:text-white transition">Features</a></li><li><a href="#" class="hover:text-white transition">Pricing</a></li><li><a href="#" class="hover:text-white transition">Docs</a></li></ul></div>\n    <div><h4 class="font-semibold text-sm mb-3 text-slate-300">Company</h4><ul class="space-y-2 text-sm text-slate-400"><li><a href="#" class="hover:text-white transition">About</a></li><li><a href="#" class="hover:text-white transition">Blog</a></li><li><a href="#" class="hover:text-white transition">Careers</a></li></ul></div>\n    <div><h4 class="font-semibold text-sm mb-3 text-slate-300">Legal</h4><ul class="space-y-2 text-sm text-slate-400"><li><a href="#" class="hover:text-white transition">Privacy</a></li><li><a href="#" class="hover:text-white transition">Terms</a></li></ul></div>\n  </div>\n  <div class="max-w-6xl mx-auto mt-12 pt-8 border-t border-slate-800 text-sm text-slate-500">© 2026 Brand. All rights reserved.</div>\n</footer>` },

  // ── E-Commerce ──
  { id: 'product-card', name: 'Product Card', category: 'E-Commerce', icon: ShoppingCart, preview: 'Product image, name, price, add to cart',
    code: `<div class="max-w-xs mx-auto bg-white rounded-2xl border border-slate-200 overflow-hidden hover:shadow-lg transition">\n  <div class="h-64 bg-gradient-to-br from-slate-100 to-slate-50 flex items-center justify-center"><span class="text-slate-300">Product Image</span></div>\n  <div class="p-5">\n    <span class="text-xs font-semibold text-cyan-600 uppercase">New Arrival</span>\n    <h3 class="font-semibold text-slate-900 mt-1 mb-1">Premium Product</h3>\n    <div class="flex items-center gap-2 mb-3"><span class="text-lg font-bold text-slate-900">$49.99</span><span class="text-sm text-slate-400 line-through">$69.99</span></div>\n    <button class="w-full py-2.5 bg-slate-900 text-white text-sm font-medium rounded-xl hover:bg-slate-800 transition">Add to Cart</button>\n  </div>\n</div>` },
  { id: 'product-grid', name: 'Product Grid', category: 'E-Commerce', icon: ShoppingCart, preview: '3-column product listing',
    code: `<section class="py-16 px-6 bg-white">\n  <div class="max-w-6xl mx-auto">\n    <h2 class="text-2xl font-bold text-slate-900 mb-8">Featured Products</h2>\n    <div class="grid md:grid-cols-3 gap-6">\n      <div class="bg-white rounded-2xl border border-slate-200 overflow-hidden hover:shadow-lg transition"><div class="h-48 bg-gradient-to-br from-cyan-50 to-blue-50"></div><div class="p-4"><h3 class="font-semibold text-slate-900 text-sm">Wireless Headphones</h3><p class="text-lg font-bold text-slate-900 mt-1">$79.99</p><button class="mt-3 w-full py-2 bg-slate-900 text-white text-xs font-medium rounded-lg hover:bg-slate-800 transition">Add to Cart</button></div></div>\n      <div class="bg-white rounded-2xl border border-slate-200 overflow-hidden hover:shadow-lg transition"><div class="h-48 bg-gradient-to-br from-violet-50 to-pink-50"></div><div class="p-4"><h3 class="font-semibold text-slate-900 text-sm">Smart Watch</h3><p class="text-lg font-bold text-slate-900 mt-1">$199.99</p><button class="mt-3 w-full py-2 bg-slate-900 text-white text-xs font-medium rounded-lg hover:bg-slate-800 transition">Add to Cart</button></div></div>\n      <div class="bg-white rounded-2xl border border-slate-200 overflow-hidden hover:shadow-lg transition"><div class="h-48 bg-gradient-to-br from-emerald-50 to-teal-50"></div><div class="p-4"><h3 class="font-semibold text-slate-900 text-sm">Laptop Stand</h3><p class="text-lg font-bold text-slate-900 mt-1">$39.99</p><button class="mt-3 w-full py-2 bg-slate-900 text-white text-xs font-medium rounded-lg hover:bg-slate-800 transition">Add to Cart</button></div></div>\n    </div>\n  </div>\n</section>` },
  { id: 'cart-summary', name: 'Cart Summary', category: 'E-Commerce', icon: ShoppingCart, preview: 'Shopping cart with totals',
    code: `<div class="max-w-md mx-auto bg-white rounded-2xl border border-slate-200 p-6">\n  <h3 class="font-bold text-slate-900 mb-4">Shopping Cart (3)</h3>\n  <div class="space-y-3 mb-4">\n    <div class="flex items-center gap-3"><div class="h-12 w-12 rounded-lg bg-slate-100"></div><div class="flex-1"><div class="text-sm font-medium text-slate-900">Wireless Headphones</div><div class="text-xs text-slate-500">Qty: 1</div></div><span class="text-sm font-semibold text-slate-900">$79.99</span></div>\n    <div class="flex items-center gap-3"><div class="h-12 w-12 rounded-lg bg-slate-100"></div><div class="flex-1"><div class="text-sm font-medium text-slate-900">Smart Watch</div><div class="text-xs text-slate-500">Qty: 1</div></div><span class="text-sm font-semibold text-slate-900">$199.99</span></div>\n  </div>\n  <div class="border-t border-slate-100 pt-3 space-y-1">\n    <div class="flex justify-between text-sm text-slate-500"><span>Subtotal</span><span>$279.98</span></div>\n    <div class="flex justify-between text-sm text-slate-500"><span>Shipping</span><span>Free</span></div>\n    <div class="flex justify-between text-sm font-bold text-slate-900 pt-2 border-t border-slate-100"><span>Total</span><span>$279.98</span></div>\n  </div>\n  <button class="w-full mt-4 py-3 bg-cyan-500 text-white font-semibold rounded-xl hover:bg-cyan-400 transition">Checkout</button>\n</div>` },

  // ── Dashboard ──
  { id: 'dashboard-cards', name: 'Dashboard KPIs', category: 'Dashboard', icon: BarChart3, preview: '4 metric cards with trends',
    code: `<div class="grid grid-cols-2 md:grid-cols-4 gap-4 p-6">\n  <div class="bg-white rounded-xl border border-slate-200 p-4"><div class="text-xs text-slate-500 mb-1">Revenue</div><div class="text-2xl font-bold text-slate-900">$12.4K</div><div class="text-xs text-emerald-500 mt-1">↑ 12.5%</div></div>\n  <div class="bg-white rounded-xl border border-slate-200 p-4"><div class="text-xs text-slate-500 mb-1">Users</div><div class="text-2xl font-bold text-slate-900">2,450</div><div class="text-xs text-emerald-500 mt-1">↑ 8.2%</div></div>\n  <div class="bg-white rounded-xl border border-slate-200 p-4"><div class="text-xs text-slate-500 mb-1">Orders</div><div class="text-2xl font-bold text-slate-900">384</div><div class="text-xs text-red-500 mt-1">↓ 3.1%</div></div>\n  <div class="bg-white rounded-xl border border-slate-200 p-4"><div class="text-xs text-slate-500 mb-1">Conversion</div><div class="text-2xl font-bold text-slate-900">3.2%</div><div class="text-xs text-emerald-500 mt-1">↑ 0.4%</div></div>\n</div>` },
  { id: 'data-table', name: 'Data Table', category: 'Dashboard', icon: Table, preview: 'Sortable data table with status',
    code: `<div class="p-6">\n  <div class="bg-white rounded-xl border border-slate-200 overflow-hidden">\n    <div class="px-4 py-3 border-b border-slate-100 flex items-center justify-between"><h3 class="font-semibold text-slate-900 text-sm">Recent Orders</h3><input placeholder="Search..." class="text-xs px-3 py-1.5 border border-slate-200 rounded-lg outline-none"></div>\n    <table class="w-full">\n      <thead><tr class="text-xs text-slate-500 border-b border-slate-100"><th class="text-left px-4 py-2.5 font-medium">Order</th><th class="text-left px-4 py-2.5 font-medium">Customer</th><th class="text-left px-4 py-2.5 font-medium">Amount</th><th class="text-left px-4 py-2.5 font-medium">Status</th></tr></thead>\n      <tbody class="text-sm">\n        <tr class="border-b border-slate-50"><td class="px-4 py-3 font-mono text-xs">#1234</td><td class="px-4 py-3 text-slate-900">Alex Kim</td><td class="px-4 py-3 text-slate-900">$245.00</td><td class="px-4 py-3"><span class="px-2 py-1 bg-emerald-50 text-emerald-600 text-xs rounded-full">Completed</span></td></tr>\n        <tr class="border-b border-slate-50"><td class="px-4 py-3 font-mono text-xs">#1235</td><td class="px-4 py-3 text-slate-900">Sarah Reyes</td><td class="px-4 py-3 text-slate-900">$189.00</td><td class="px-4 py-3"><span class="px-2 py-1 bg-amber-50 text-amber-600 text-xs rounded-full">Pending</span></td></tr>\n        <tr><td class="px-4 py-3 font-mono text-xs">#1236</td><td class="px-4 py-3 text-slate-900">Mike Johnson</td><td class="px-4 py-3 text-slate-900">$512.00</td><td class="px-4 py-3"><span class="px-2 py-1 bg-blue-50 text-blue-600 text-xs rounded-full">Processing</span></td></tr>\n      </tbody>\n    </table>\n  </div>\n</div>` },

  // ── Notifications ──
  { id: 'notification-toast', name: 'Toast Notifications', category: 'UI Elements', icon: Bell, preview: 'Success, error, info toast alerts',
    code: `<div class="fixed top-4 right-4 space-y-3 z-50 w-80">\n  <div class="bg-white rounded-xl border border-slate-200 shadow-lg p-4 flex items-start gap-3"><span class="text-emerald-500 text-lg mt-0.5">✓</span><div><div class="text-sm font-semibold text-slate-900">Success</div><div class="text-xs text-slate-500 mt-0.5">Your changes have been saved successfully.</div></div><button class="text-slate-300 hover:text-slate-500 ml-auto">✕</button></div>\n  <div class="bg-white rounded-xl border border-red-200 shadow-lg p-4 flex items-start gap-3"><span class="text-red-500 text-lg mt-0.5">✕</span><div><div class="text-sm font-semibold text-slate-900">Error</div><div class="text-xs text-slate-500 mt-0.5">Something went wrong. Please try again.</div></div><button class="text-slate-300 hover:text-slate-500 ml-auto">✕</button></div>\n</div>` },
  { id: 'empty-state', name: 'Empty State', category: 'UI Elements', icon: Square, preview: 'No data placeholder with CTA',
    code: `<div class="flex flex-col items-center justify-center py-24 px-6 text-center">\n  <div class="h-16 w-16 rounded-2xl bg-slate-100 flex items-center justify-center mb-6"><span class="text-3xl">📦</span></div>\n  <h3 class="text-lg font-semibold text-slate-900 mb-2">No items yet</h3>\n  <p class="text-sm text-slate-500 mb-6 max-w-sm">Get started by creating your first item. It only takes a few seconds.</p>\n  <button class="px-6 py-2.5 bg-slate-900 text-white text-sm font-medium rounded-xl hover:bg-slate-800 transition">Create Item</button>\n</div>` },
];

const CATEGORIES = [...new Set(COMPONENTS.map(c => c.category))];

export function ComponentPalette({ open, onClose, onInsertComponent }: ComponentPaletteProps) {
  const [searchQuery, setSearchQuery] = useState('');
  const [expandedCategories, setExpandedCategories] = useState<Set<string>>(new Set(CATEGORIES));
  const [draggingId, setDraggingId] = useState<string | null>(null);

  const filtered = searchQuery.trim()
    ? COMPONENTS.filter(c => c.name.toLowerCase().includes(searchQuery.toLowerCase()) || c.category.toLowerCase().includes(searchQuery.toLowerCase()))
    : COMPONENTS;

  const handleDragStart = useCallback((e: React.DragEvent, component: ComponentTemplate) => {
    setDraggingId(component.id);
    e.dataTransfer.setData('text/plain', component.code);
    e.dataTransfer.effectAllowed = 'copy';
  }, []);

  const toggleCategory = (cat: string) => {
    setExpandedCategories(prev => {
      const next = new Set(prev);
      if (next.has(cat)) next.delete(cat); else next.add(cat);
      return next;
    });
  };

  if (!open) return null;

  return (
    <div className="w-64 border-r border-white/[0.06] bg-[#0d0d14] flex flex-col h-full">
      <div className="px-3 py-2.5 border-b border-white/[0.06] flex items-center justify-between">
        <div className="flex items-center gap-2">
          <Sparkles className="h-3.5 w-3.5 text-violet-400" />
          <span className="text-xs font-semibold text-white/70">Components</span>
          <span className="text-[9px] text-white/20 font-mono">{COMPONENTS.length}</span>
        </div>
        <button onClick={onClose} className="text-white/20 hover:text-white/50 text-xs">✕</button>
      </div>

      {/* Search */}
      <div className="px-2 py-1.5 border-b border-white/[0.04]">
        <div className="flex items-center gap-1.5 bg-white/[0.03] border border-white/[0.06] rounded-md px-2 h-6">
          <Search className="h-2.5 w-2.5 text-white/20 shrink-0" />
          <input
            value={searchQuery}
            onChange={e => setSearchQuery(e.target.value)}
            placeholder="Search components..."
            className="flex-1 bg-transparent text-[10px] text-white/60 placeholder:text-white/15 outline-none"
          />
        </div>
      </div>

      <ScrollArea className="flex-1">
        <div className="py-1">
          {CATEGORIES.map(cat => {
            const items = filtered.filter(c => c.category === cat);
            if (items.length === 0) return null;
            const isExpanded = expandedCategories.has(cat);

            return (
              <div key={cat}>
                <button
                  onClick={() => toggleCategory(cat)}
                  className="w-full flex items-center gap-1.5 px-3 py-1.5 text-[10px] font-semibold text-white/30 uppercase tracking-widest hover:text-white/50 transition-colors"
                >
                  {isExpanded ? <ChevronDown className="h-2.5 w-2.5" /> : <ChevronRight className="h-2.5 w-2.5" />}
                  {cat}
                  <span className="text-white/15 ml-auto font-mono">{items.length}</span>
                </button>
                {isExpanded && items.map(comp => (
                  <div
                    key={comp.id}
                    draggable
                    onDragStart={(e) => handleDragStart(e, comp)}
                    onDragEnd={() => setDraggingId(null)}
                    className={cn(
                      "flex items-center gap-2 px-3 py-2 mx-1 rounded-lg cursor-grab transition-all group",
                      draggingId === comp.id
                        ? "bg-violet-500/10 border border-violet-500/20"
                        : "hover:bg-white/[0.03] border border-transparent"
                    )}
                  >
                    <GripVertical className="h-3 w-3 text-white/10 group-hover:text-white/25 shrink-0" />
                    <comp.icon className="h-3.5 w-3.5 text-white/25 shrink-0" />
                    <div className="flex-1 min-w-0">
                      <div className="text-[11px] text-white/60 font-medium truncate">{comp.name}</div>
                      <div className="text-[9px] text-white/20 truncate">{comp.preview}</div>
                    </div>
                    <button
                      onClick={() => { onInsertComponent(comp.code); toast.success(`Inserted ${comp.name}`); }}
                      className="opacity-0 group-hover:opacity-100 text-[9px] text-cyan-400/70 hover:text-cyan-400 bg-cyan-500/10 px-1.5 py-0.5 rounded transition-all shrink-0"
                    >
                      Add
                    </button>
                  </div>
                ))}
              </div>
            );
          })}
        </div>
      </ScrollArea>
    </div>
  );
}
