import JSZip from 'jszip';
import type { ProjectFile } from '@/hooks/useProjectFileSystem';

const slugify = (name: string) =>
  name.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '') || 'my-app';

/** Generate scaffolding files for a Docker-ready React+Vite project */
function getScaffoldingFiles(projectName: string, userFiles: ProjectFile[]): Record<string, string> {
  const slug = slugify(projectName);

  const packageJson = JSON.stringify({
    name: slug,
    private: true,
    version: '1.0.0',
    type: 'module',
    scripts: {
      dev: 'vite',
      build: 'vite build',
      preview: 'vite preview',
    },
    dependencies: {
      react: '^18.3.1',
      'react-dom': '^18.3.1',
    },
    devDependencies: {
      '@vitejs/plugin-react': '^4.3.4',
      vite: '^6.0.0',
    },
  }, null, 2);

  const viteConfig = `import { defineConfig } from 'vite';
import react from '@vitejs/plugin-react';

export default defineConfig({
  plugins: [react()],
  server: { host: true, port: 3000 },
});
`;

  const indexHtml = `<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>${projectName}</title>
  </head>
  <body>
    <div id="root"></div>
    <script type="module" src="/src/main.jsx"></script>
  </body>
</html>
`;

  const mainJsx = `import React from 'react';
import ReactDOM from 'react-dom/client';
import App from './App';

ReactDOM.createRoot(document.getElementById('root')).render(
  <React.StrictMode>
    <App />
  </React.StrictMode>
);
`;

  // Build App.jsx that inlines the user's HTML/CSS/JS
  const htmlFile = userFiles.find(f => f.path === 'index.html') || userFiles.find(f => f.language === 'html');
  const cssFiles = userFiles.filter(f => f.language === 'css');
  const jsFiles = userFiles.filter(f => f.language === 'javascript' || f.language === 'typescript');

  const cssImports = cssFiles.map((f, i) => `import './user-styles-${i}.css';`).join('\n');

  const appJsx = `import React, { useEffect, useRef } from 'react';
${cssImports}

const USER_HTML = ${JSON.stringify(htmlFile?.content || '<div>No HTML content</div>')};
const USER_SCRIPTS = ${JSON.stringify(jsFiles.map(f => f.content))};

export default function App() {
  const containerRef = useRef(null);

  useEffect(() => {
    if (!containerRef.current) return;
    // Execute user scripts after mount
    for (const script of USER_SCRIPTS) {
      try {
        const fn = new Function(script);
        fn();
      } catch (e) {
        console.warn('Script error:', e);
      }
    }
  }, []);

  return (
    <div
      ref={containerRef}
      dangerouslySetInnerHTML={{ __html: USER_HTML }}
    />
  );
}
`;

  const dockerfile = `# Stage 1: Build
FROM node:20-alpine AS build
WORKDIR /app
COPY package.json ./
RUN npm install
COPY . .
RUN npm run build

# Stage 2: Serve
FROM nginx:alpine
COPY --from=build /app/dist /usr/share/nginx/html
COPY nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
`;

  const nginxConf = `server {
    listen 80;
    server_name localhost;
    root /usr/share/nginx/html;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }

    location ~* \\.(js|css|png|jpg|jpeg|gif|ico|svg|woff|woff2|ttf|eot)$ {
        expires 1y;
        add_header Cache-Control "public, immutable";
    }

    gzip on;
    gzip_types text/plain text/css application/json application/javascript text/xml;
}
`;

  const dockerIgnore = `node_modules
dist
.git
.gitignore
*.md
`;

  const readme = `# ${projectName}

Generated by AI App Builder.

## Development

\`\`\`bash
npm install
npm run dev
\`\`\`

## Docker Deployment

\`\`\`bash
docker build -t ${slug} .
docker run -p 8080:80 ${slug}
\`\`\`

Then open http://localhost:8080
`;

  const files: Record<string, string> = {
    'package.json': packageJson,
    'vite.config.js': viteConfig,
    'index.html': indexHtml,
    'src/main.jsx': mainJsx,
    'src/App.jsx': appJsx,
    'Dockerfile': dockerfile,
    'nginx.conf': nginxConf,
    '.dockerignore': dockerIgnore,
    'README.md': readme,
  };

  // Add user CSS files
  cssFiles.forEach((f, i) => {
    files[`src/user-styles-${i}.css`] = f.content;
  });

  return files;
}

export type ExportMode = 'raw' | 'docker';

export async function exportProject(
  projectName: string,
  files: ProjectFile[],
  mode: ExportMode
): Promise<void> {
  const zip = new JSZip();
  const slug = slugify(projectName);

  if (mode === 'raw') {
    // Simple export: just the user's files as-is
    for (const file of files) {
      zip.file(file.path, file.content);
    }
  } else {
    // Docker-ready React+Vite project
    const scaffolding = getScaffoldingFiles(projectName, files);
    for (const [path, content] of Object.entries(scaffolding)) {
      zip.file(path, content);
    }
    // Also include original source files in a src/original/ folder
    for (const file of files) {
      zip.file(`src/original/${file.path}`, file.content);
    }
  }

  const blob = await zip.generateAsync({ type: 'blob' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = `${slug}${mode === 'docker' ? '-docker' : ''}.zip`;
  a.click();
  URL.revokeObjectURL(url);
}
