import { useState } from 'react';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import {
  Dialog, DialogContent, DialogHeader, DialogTitle, DialogTrigger, DialogDescription, DialogFooter,
} from '@/components/ui/dialog';
import { Github, Loader2, ArrowUpFromLine, ArrowDownToLine, CheckCircle, AlertCircle } from 'lucide-react';
import { toast } from 'sonner';
import { supabase } from '@/integrations/supabase/client';
import type { ProjectFile } from '@/hooks/useProjectFileSystem';
import { cn } from '@/lib/utils';

type SyncStatus = 'synced' | 'ahead' | 'behind' | 'unknown';

interface GithubSyncButtonProps {
  projectName: string;
  files: ProjectFile[];
  githubToken: string;
  onPullFiles?: (files: ProjectFile[]) => void;
}

export function GithubSyncButton({ projectName, files, githubToken, onPullFiles }: GithubSyncButtonProps) {
  const [open, setOpen] = useState(false);
  const [repoName, setRepoName] = useState(
    projectName.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '') || 'my-app'
  );
  const [repoFullName, setRepoFullName] = useState('');
  const [isPrivate, setIsPrivate] = useState(true);
  const [isPushing, setIsPushing] = useState(false);
  const [isPulling, setIsPulling] = useState(false);
  const [syncStatus, setSyncStatus] = useState<SyncStatus>('unknown');

  const handlePush = async () => {
    if (!repoName.trim()) return;
    setIsPushing(true);

    try {
      const { data, error } = await supabase.functions.invoke('github-push', {
        body: {
          token: githubToken,
          repoName: repoName.trim(),
          isPrivate,
          files: files.map(f => ({ path: f.path, content: f.content })),
          description: `Generated by AI App Builder — ${projectName}`,
        },
      });

      if (error) throw error;
      if (data?.error) throw new Error(data.error);

      setSyncStatus('synced');
      if (data?.repoUrl) {
        // Extract full name for pull
        const match = data.repoUrl.match(/github\.com\/(.+)/);
        if (match) setRepoFullName(match[1]);
      }
      toast.success('Pushed to GitHub!', {
        description: data?.repoUrl,
        action: data?.repoUrl ? {
          label: 'Open',
          onClick: () => window.open(data.repoUrl, '_blank'),
        } : undefined,
      });
    } catch (e: any) {
      console.error('GitHub push error:', e);
      toast.error(e.message || 'Failed to push to GitHub');
    } finally {
      setIsPushing(false);
    }
  };

  const handlePull = async () => {
    const pullTarget = repoFullName.trim();
    if (!pullTarget) {
      toast.error('Enter the full repo name (owner/repo) to pull from');
      return;
    }
    setIsPulling(true);

    try {
      const { data, error } = await supabase.functions.invoke('github-pull', {
        body: {
          token: githubToken,
          repoFullName: pullTarget,
        },
      });

      if (error) throw error;
      if (data?.error) throw new Error(data.error);

      if (data?.files && data.files.length > 0 && onPullFiles) {
        onPullFiles(data.files);
        setSyncStatus('synced');
        toast.success(`Pulled ${data.fetchedFiles} files from GitHub`);
      } else {
        toast.info('No files found in repository');
      }
    } catch (e: any) {
      console.error('GitHub pull error:', e);
      toast.error(e.message || 'Failed to pull from GitHub');
    } finally {
      setIsPulling(false);
    }
  };

  const isLoading = isPushing || isPulling;

  return (
    <Dialog open={open} onOpenChange={setOpen}>
      <DialogTrigger asChild>
        <Button variant="outline" size="sm" className="h-7 text-xs gap-1.5">
          <Github className="h-3 w-3" />
          Sync
          {syncStatus === 'synced' && <span className="h-1.5 w-1.5 rounded-full bg-emerald-400" />}
          {syncStatus === 'ahead' && <span className="h-1.5 w-1.5 rounded-full bg-amber-400" />}
          {syncStatus === 'behind' && <span className="h-1.5 w-1.5 rounded-full bg-blue-400" />}
        </Button>
      </DialogTrigger>
      <DialogContent className="sm:max-w-md bg-[#0d0d14] border-white/[0.08] text-white">
        <DialogHeader>
          <DialogTitle className="flex items-center gap-2">
            <Github className="h-5 w-5" />
            GitHub Sync
          </DialogTitle>
          <DialogDescription className="text-white/40">
            Push and pull your {files.length} project files with GitHub.
          </DialogDescription>
        </DialogHeader>

        <div className="space-y-4 py-2">
          <div className="space-y-1.5">
            <Label htmlFor="repo-name" className="text-xs text-white/60">Repository Name (for push)</Label>
            <Input
              id="repo-name"
              value={repoName}
              onChange={(e) => setRepoName(e.target.value)}
              placeholder="my-awesome-app"
              className="text-sm font-mono bg-white/[0.03] border-white/[0.08] text-white/80"
            />
          </div>

          <div className="space-y-1.5">
            <Label htmlFor="repo-full" className="text-xs text-white/60">Full Repo Name (for pull)</Label>
            <Input
              id="repo-full"
              value={repoFullName}
              onChange={(e) => setRepoFullName(e.target.value)}
              placeholder="username/repo-name"
              className="text-sm font-mono bg-white/[0.03] border-white/[0.08] text-white/80"
            />
          </div>

          <div className="flex items-center gap-2">
            <input
              type="checkbox"
              id="private-repo"
              checked={isPrivate}
              onChange={(e) => setIsPrivate(e.target.checked)}
              className="rounded"
            />
            <Label htmlFor="private-repo" className="text-xs text-white/60">Private repository</Label>
          </div>

          {/* Sync status */}
          <div className="flex items-center gap-2 p-2 rounded-lg bg-white/[0.03] border border-white/[0.06]">
            {syncStatus === 'synced' ? (
              <><CheckCircle className="h-3.5 w-3.5 text-emerald-400" /><span className="text-xs text-emerald-400">In sync</span></>
            ) : syncStatus === 'ahead' ? (
              <><AlertCircle className="h-3.5 w-3.5 text-amber-400" /><span className="text-xs text-amber-400">Local changes not pushed</span></>
            ) : syncStatus === 'behind' ? (
              <><AlertCircle className="h-3.5 w-3.5 text-blue-400" /><span className="text-xs text-blue-400">Remote changes available</span></>
            ) : (
              <><Github className="h-3.5 w-3.5 text-white/30" /><span className="text-xs text-white/30">Not yet synced</span></>
            )}
          </div>
        </div>

        <DialogFooter className="gap-2">
          <Button
            onClick={handlePull}
            disabled={isLoading || !repoFullName.trim()}
            variant="outline"
            size="sm"
            className="border-white/[0.08] text-white/60 hover:text-white/80"
          >
            {isPulling ? (
              <Loader2 className="h-3 w-3 mr-1 animate-spin" />
            ) : (
              <ArrowDownToLine className="h-3 w-3 mr-1" />
            )}
            Pull
          </Button>
          <Button onClick={handlePush} disabled={isLoading || !repoName.trim()} size="sm">
            {isPushing ? (
              <Loader2 className="h-3 w-3 mr-1 animate-spin" />
            ) : (
              <ArrowUpFromLine className="h-3 w-3 mr-1" />
            )}
            Push
          </Button>
        </DialogFooter>
      </DialogContent>
    </Dialog>
  );
}
