import { useState } from 'react';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import {
  Dialog, DialogContent, DialogHeader, DialogTitle, DialogTrigger, DialogDescription, DialogFooter,
} from '@/components/ui/dialog';
import { Github, Loader2 } from 'lucide-react';
import { toast } from 'sonner';
import { supabase } from '@/integrations/supabase/client';
import type { ProjectFile } from '@/hooks/useProjectFileSystem';

interface GithubPushButtonProps {
  projectName: string;
  files: ProjectFile[];
  githubToken: string;
}

export function GithubPushButton({ projectName, files, githubToken }: GithubPushButtonProps) {
  const [open, setOpen] = useState(false);
  const [repoName, setRepoName] = useState(
    projectName.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '') || 'my-app'
  );
  const [isPrivate, setIsPrivate] = useState(true);
  const [isPushing, setIsPushing] = useState(false);

  const handlePush = async () => {
    if (!repoName.trim()) return;
    setIsPushing(true);

    try {
      const { data, error } = await supabase.functions.invoke('github-push', {
        body: {
          token: githubToken,
          repoName: repoName.trim(),
          isPrivate,
          files: files.map(f => ({ path: f.path, content: f.content })),
          description: `Generated by AI App Builder — ${projectName}`,
        },
      });

      if (error) throw error;
      if (data?.error) throw new Error(data.error);

      toast.success('Pushed to GitHub!', {
        description: data?.repoUrl,
        action: data?.repoUrl ? {
          label: 'Open',
          onClick: () => window.open(data.repoUrl, '_blank'),
        } : undefined,
      });
      setOpen(false);
    } catch (e: any) {
      console.error('GitHub push error:', e);
      toast.error(e.message || 'Failed to push to GitHub');
    } finally {
      setIsPushing(false);
    }
  };

  return (
    <Dialog open={open} onOpenChange={setOpen}>
      <DialogTrigger asChild>
        <Button variant="outline" size="sm" className="h-7 text-xs gap-1.5">
          <Github className="h-3 w-3" />
          Push to GitHub
        </Button>
      </DialogTrigger>
      <DialogContent className="sm:max-w-md">
        <DialogHeader>
          <DialogTitle className="flex items-center gap-2">
            <Github className="h-5 w-5" />
            Push to GitHub
          </DialogTitle>
          <DialogDescription>
            Create a new repository and push your {files.length} project files.
          </DialogDescription>
        </DialogHeader>

        <div className="space-y-4 py-2">
          <div className="space-y-1.5">
            <Label htmlFor="repo-name" className="text-xs">Repository Name</Label>
            <Input
              id="repo-name"
              value={repoName}
              onChange={(e) => setRepoName(e.target.value)}
              placeholder="my-awesome-app"
              className="text-sm font-mono"
            />
          </div>
          <div className="flex items-center gap-2">
            <input
              type="checkbox"
              id="private-repo"
              checked={isPrivate}
              onChange={(e) => setIsPrivate(e.target.checked)}
              className="rounded"
            />
            <Label htmlFor="private-repo" className="text-xs">Private repository</Label>
          </div>
        </div>

        <DialogFooter>
          <Button onClick={handlePush} disabled={isPushing || !repoName.trim()} size="sm">
            {isPushing ? (
              <>
                <Loader2 className="h-3 w-3 mr-1 animate-spin" />
                Pushing...
              </>
            ) : (
              <>
                <Github className="h-3 w-3 mr-1" />
                Create & Push
              </>
            )}
          </Button>
        </DialogFooter>
      </DialogContent>
    </Dialog>
  );
}
