import { serve } from "https://deno.land/std@0.190.0/http/server.ts";
import { createClient } from "https://esm.sh/@supabase/supabase-js@2.57.2";

const corsHeaders = {
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Headers': 'authorization, x-client-info, apikey, content-type',
};

const logStep = (step: string, details?: any) => {
  const detailsStr = details ? ` - ${JSON.stringify(details)}` : '';
  console.log(`[SENTINEL-AI-TRIAGE] ${step}${detailsStr}`);
};

interface SecurityEvent {
  id: string;
  event_type: string;
  severity: string;
  affected_user: string;
  ip_address: string;
  location: string;
  raw_event_data: any;
  ai_risk_score?: number;
}

interface TriageDecision {
  action: 'auto_resolve' | 'escalate' | 'create_ticket' | 'monitor';
  confidence: number;
  reasoning: string;
  recommendedPriority: 'low' | 'medium' | 'high' | 'critical';
}

function analyzeEvent(event: SecurityEvent): TriageDecision {
  const riskScore = event.ai_risk_score || 50;
  
  // High-confidence auto-resolution patterns
  const autoResolvePatterns = [
    // Known safe IPs (example - in production, check against whitelist)
    event.ip_address?.startsWith('10.') || event.ip_address?.startsWith('192.168.'),
    // Low risk score with policy enforcement
    riskScore < 30 && event.event_type === 'conditional_access',
    // Known corporate locations
    event.location?.toLowerCase().includes('headquarters')
  ];

  if (autoResolvePatterns.some(p => p)) {
    return {
      action: 'auto_resolve',
      confidence: 0.85,
      reasoning: 'Event matches known safe patterns (internal IP or corporate location)',
      recommendedPriority: 'low'
    };
  }

  // Critical escalation patterns
  const criticalPatterns = [
    riskScore >= 85,
    event.event_type === 'risky_signin' && event.raw_event_data?.riskEventType === 'impossibleTravel',
    event.event_type === 'mailbox_rule' && event.raw_event_data?.forwardTo?.includes('@'),
    event.severity === 'critical'
  ];

  if (criticalPatterns.some(p => p)) {
    return {
      action: 'create_ticket',
      confidence: 0.92,
      reasoning: 'Critical threat indicators detected - immediate action required',
      recommendedPriority: 'critical'
    };
  }

  // High-priority ticket creation
  if (riskScore >= 60 || event.severity === 'high') {
    return {
      action: 'create_ticket',
      confidence: 0.78,
      reasoning: 'Elevated risk score requires human review',
      recommendedPriority: 'high'
    };
  }

  // Medium risk - escalate for review
  if (riskScore >= 40) {
    return {
      action: 'escalate',
      confidence: 0.65,
      reasoning: 'Moderate risk - recommend technician review',
      recommendedPriority: 'medium'
    };
  }

  // Low risk - monitor only
  return {
    action: 'monitor',
    confidence: 0.70,
    reasoning: 'Low risk event - logging for pattern analysis',
    recommendedPriority: 'low'
  };
}

async function createTicketFromEvent(
  supabase: any, 
  event: SecurityEvent, 
  decision: TriageDecision,
  userId: string
) {
  const priorityMap = { low: 'low', medium: 'medium', high: 'high', critical: 'urgent' };
  
  const ticketData = {
    user_id: userId,
    title: `[Sentinel] ${event.event_type.replace('_', ' ').toUpperCase()}: ${event.affected_user}`,
    description: `
## Security Alert Auto-Generated by Vanguard Sentinel

**Event Type:** ${event.event_type}
**Affected User:** ${event.affected_user}
**Location:** ${event.location || 'Unknown'}
**IP Address:** ${event.ip_address || 'Unknown'}
**Risk Score:** ${event.ai_risk_score || 'N/A'}

### AI Analysis
**Confidence:** ${(decision.confidence * 100).toFixed(0)}%
**Reasoning:** ${decision.reasoning}

### Recommended Actions
1. Verify user identity
2. Review recent activity
3. Check for additional indicators of compromise
4. Update user if action taken
    `.trim(),
    status: 'open',
    priority: priorityMap[decision.recommendedPriority],
    category: 'security',
    source: 'sentinel_ai',
    metadata: {
      sentinel_event_id: event.id,
      ai_triage_decision: decision,
      original_event_data: event.raw_event_data
    }
  };

  const { data: ticket, error } = await supabase
    .from('vanguard_tickets')
    .insert(ticketData)
    .select()
    .single();

  if (error) {
    logStep('Failed to create ticket', { error });
    return null;
  }

  return ticket;
}

serve(async (req) => {
  if (req.method === 'OPTIONS') {
    return new Response(null, { headers: corsHeaders });
  }

  const supabase = createClient(
    Deno.env.get('SUPABASE_URL') ?? '',
    Deno.env.get('SUPABASE_SERVICE_ROLE_KEY') ?? ''
  );

  try {
    const { action, eventId, eventIds } = await req.json();
    logStep('Triage request', { action, eventId, eventIds });

    if (action === 'triage_single' && eventId) {
      // Triage a single event
      const { data: event, error: eventError } = await supabase
        .from('vanguard_m365_security_events')
        .select('*')
        .eq('id', eventId)
        .single();

      if (eventError || !event) {
        throw new Error('Event not found');
      }

      const decision = analyzeEvent(event);
      logStep('Triage decision', { eventId, decision });

      // Store AI analysis
      await supabase
        .from('vanguard_sentinel_ai_analysis')
        .insert({
          event_id: eventId,
          user_id: event.user_id,
          risk_score: event.ai_risk_score || 50,
          threat_category: event.ai_threat_category || 'Unknown',
          recommendation: decision.reasoning,
          confidence_score: decision.confidence,
          auto_action_taken: decision.action,
          ticket_created: decision.action === 'create_ticket'
        });

      // Create ticket if needed
      let ticket = null;
      if (decision.action === 'create_ticket') {
        ticket = await createTicketFromEvent(supabase, event, decision, event.user_id);
        
        // Update event with ticket reference
        if (ticket) {
          await supabase
            .from('vanguard_m365_security_events')
            .update({ 
              status: 'escalated',
              ticket_id: ticket.id 
            })
            .eq('id', eventId);
        }
      } else if (decision.action === 'auto_resolve') {
        await supabase
          .from('vanguard_m365_security_events')
          .update({ status: 'auto_resolved' })
          .eq('id', eventId);
      }

      return new Response(JSON.stringify({
        success: true,
        decision,
        ticketCreated: !!ticket,
        ticketId: ticket?.id
      }), {
        headers: { ...corsHeaders, 'Content-Type': 'application/json' }
      });
    }

    if (action === 'triage_batch') {
      // Process multiple events
      const { data: events, error: eventsError } = await supabase
        .from('vanguard_m365_security_events')
        .select('*')
        .in('status', ['new', 'pending'])
        .order('created_at', { ascending: false })
        .limit(50);

      if (eventsError) throw eventsError;

      const results = {
        processed: 0,
        autoResolved: 0,
        ticketsCreated: 0,
        escalated: 0,
        monitored: 0
      };

      for (const event of events || []) {
        const decision = analyzeEvent(event);
        results.processed++;

        // Store analysis
        await supabase
          .from('vanguard_sentinel_ai_analysis')
          .insert({
            event_id: event.id,
            user_id: event.user_id,
            risk_score: event.ai_risk_score || 50,
            threat_category: event.ai_threat_category || 'Unknown',
            recommendation: decision.reasoning,
            confidence_score: decision.confidence,
            auto_action_taken: decision.action,
            ticket_created: decision.action === 'create_ticket'
          });

        switch (decision.action) {
          case 'auto_resolve':
            await supabase
              .from('vanguard_m365_security_events')
              .update({ status: 'auto_resolved' })
              .eq('id', event.id);
            results.autoResolved++;
            break;

          case 'create_ticket':
            const ticket = await createTicketFromEvent(supabase, event, decision, event.user_id);
            if (ticket) {
              await supabase
                .from('vanguard_m365_security_events')
                .update({ status: 'escalated', ticket_id: ticket.id })
                .eq('id', event.id);
              results.ticketsCreated++;
            }
            break;

          case 'escalate':
            await supabase
              .from('vanguard_m365_security_events')
              .update({ status: 'needs_review' })
              .eq('id', event.id);
            results.escalated++;
            break;

          case 'monitor':
            await supabase
              .from('vanguard_m365_security_events')
              .update({ status: 'monitored' })
              .eq('id', event.id);
            results.monitored++;
            break;
        }
      }

      logStep('Batch triage complete', results);

      return new Response(JSON.stringify({
        success: true,
        results
      }), {
        headers: { ...corsHeaders, 'Content-Type': 'application/json' }
      });
    }

    if (action === 'get_stats') {
      // Get triage statistics
      const { data: stats } = await supabase
        .from('vanguard_sentinel_ai_analysis')
        .select('auto_action_taken, ticket_created')
        .gte('created_at', new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString());

      const summary = {
        totalAnalyzed: stats?.length || 0,
        autoResolved: stats?.filter(s => s.auto_action_taken === 'auto_resolve').length || 0,
        ticketsCreated: stats?.filter(s => s.ticket_created).length || 0,
        escalated: stats?.filter(s => s.auto_action_taken === 'escalate').length || 0,
        monitored: stats?.filter(s => s.auto_action_taken === 'monitor').length || 0
      };

      return new Response(JSON.stringify({ success: true, stats: summary }), {
        headers: { ...corsHeaders, 'Content-Type': 'application/json' }
      });
    }

    return new Response(JSON.stringify({ error: 'Invalid action' }), {
      headers: { ...corsHeaders, 'Content-Type': 'application/json' },
      status: 400
    });

  } catch (error) {
    const errorMessage = error instanceof Error ? error.message : 'Unknown error';
    logStep('ERROR', { message: errorMessage });
    return new Response(JSON.stringify({ error: errorMessage }), {
      headers: { ...corsHeaders, 'Content-Type': 'application/json' },
      status: 500
    });
  }
});
