import React, { createContext, useContext, useState, useEffect, ReactNode } from 'react';

export type Language = 'en' | 'es' | 'fr' | 'de' | 'pt' | 'ja' | 'zh' | 'ko';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
  languages: { code: Language; name: string; flag: string }[];
}

const languages = [
  { code: 'en' as Language, name: 'English', flag: '🇺🇸' },
  { code: 'es' as Language, name: 'Español', flag: '🇪🇸' },
  { code: 'fr' as Language, name: 'Français', flag: '🇫🇷' },
  { code: 'de' as Language, name: 'Deutsch', flag: '🇩🇪' },
  { code: 'pt' as Language, name: 'Português', flag: '🇧🇷' },
  { code: 'ja' as Language, name: '日本語', flag: '🇯🇵' },
  { code: 'zh' as Language, name: '中文', flag: '🇨🇳' },
  { code: 'ko' as Language, name: '한국어', flag: '🇰🇷' },
];

// Translation dictionary
const translations: Record<Language, Record<string, string>> = {
  en: {
    // Navigation
    'nav.dashboard': 'Dashboard',
    'nav.tickets': 'Tickets',
    'nav.customers': 'Customers',
    'nav.devices': 'Devices',
    'nav.alerts': 'Alerts',
    'nav.reports': 'Reports',
    'nav.settings': 'Settings',
    'nav.cortex': 'Cortex AI Hub',
    
    // Common
    'common.save': 'Save',
    'common.cancel': 'Cancel',
    'common.delete': 'Delete',
    'common.edit': 'Edit',
    'common.create': 'Create',
    'common.search': 'Search',
    'common.filter': 'Filter',
    'common.export': 'Export',
    'common.import': 'Import',
    'common.loading': 'Loading...',
    'common.noData': 'No data available',
    'common.success': 'Success',
    'common.error': 'Error',
    'common.warning': 'Warning',
    'common.info': 'Info',
    
    // Tickets
    'tickets.title': 'Tickets',
    'tickets.new': 'New Ticket',
    'tickets.open': 'Open',
    'tickets.closed': 'Closed',
    'tickets.pending': 'Pending',
    'tickets.priority': 'Priority',
    'tickets.assignee': 'Assignee',
    
    // Dashboard
    'dashboard.welcome': 'Welcome to Vanguard',
    'dashboard.overview': 'Overview',
    'dashboard.recentActivity': 'Recent Activity',
    'dashboard.quickActions': 'Quick Actions',
    
    // Cortex AI
    'cortex.hub': 'Cortex AI Hub',
    'cortex.tools': 'AI Tools',
    'cortex.settings': 'AI Settings',
    'cortex.analytics': 'AI Analytics',
    
    // Notifications
    'notifications.title': 'Notifications',
    'notifications.markRead': 'Mark as Read',
    'notifications.clearAll': 'Clear All',
    'notifications.noNew': 'No new notifications',
  },
  es: {
    // Navigation
    'nav.dashboard': 'Panel',
    'nav.tickets': 'Tickets',
    'nav.customers': 'Clientes',
    'nav.devices': 'Dispositivos',
    'nav.alerts': 'Alertas',
    'nav.reports': 'Informes',
    'nav.settings': 'Configuración',
    'nav.cortex': 'Centro de IA Cortex',
    
    // Common
    'common.save': 'Guardar',
    'common.cancel': 'Cancelar',
    'common.delete': 'Eliminar',
    'common.edit': 'Editar',
    'common.create': 'Crear',
    'common.search': 'Buscar',
    'common.filter': 'Filtrar',
    'common.export': 'Exportar',
    'common.import': 'Importar',
    'common.loading': 'Cargando...',
    'common.noData': 'Sin datos disponibles',
    'common.success': 'Éxito',
    'common.error': 'Error',
    'common.warning': 'Advertencia',
    'common.info': 'Información',
    
    // Tickets
    'tickets.title': 'Tickets',
    'tickets.new': 'Nuevo Ticket',
    'tickets.open': 'Abierto',
    'tickets.closed': 'Cerrado',
    'tickets.pending': 'Pendiente',
    'tickets.priority': 'Prioridad',
    'tickets.assignee': 'Asignado',
    
    // Dashboard
    'dashboard.welcome': 'Bienvenido a Vanguard',
    'dashboard.overview': 'Resumen',
    'dashboard.recentActivity': 'Actividad Reciente',
    'dashboard.quickActions': 'Acciones Rápidas',
    
    // Cortex AI
    'cortex.hub': 'Centro de IA Cortex',
    'cortex.tools': 'Herramientas de IA',
    'cortex.settings': 'Configuración de IA',
    'cortex.analytics': 'Análisis de IA',
    
    // Notifications
    'notifications.title': 'Notificaciones',
    'notifications.markRead': 'Marcar como Leído',
    'notifications.clearAll': 'Limpiar Todo',
    'notifications.noNew': 'Sin notificaciones nuevas',
  },
  fr: {
    'nav.dashboard': 'Tableau de bord',
    'nav.tickets': 'Tickets',
    'nav.customers': 'Clients',
    'nav.devices': 'Appareils',
    'nav.alerts': 'Alertes',
    'nav.reports': 'Rapports',
    'nav.settings': 'Paramètres',
    'nav.cortex': 'Centre IA Cortex',
    'common.save': 'Enregistrer',
    'common.cancel': 'Annuler',
    'common.delete': 'Supprimer',
    'common.edit': 'Modifier',
    'common.create': 'Créer',
    'common.search': 'Rechercher',
    'common.filter': 'Filtrer',
    'common.export': 'Exporter',
    'common.import': 'Importer',
    'common.loading': 'Chargement...',
    'common.noData': 'Aucune donnée disponible',
    'common.success': 'Succès',
    'common.error': 'Erreur',
    'common.warning': 'Avertissement',
    'common.info': 'Info',
    'tickets.title': 'Tickets',
    'tickets.new': 'Nouveau Ticket',
    'tickets.open': 'Ouvert',
    'tickets.closed': 'Fermé',
    'tickets.pending': 'En attente',
    'tickets.priority': 'Priorité',
    'tickets.assignee': 'Assigné',
    'dashboard.welcome': 'Bienvenue sur Vanguard',
    'dashboard.overview': 'Aperçu',
    'dashboard.recentActivity': 'Activité Récente',
    'dashboard.quickActions': 'Actions Rapides',
    'cortex.hub': 'Centre IA Cortex',
    'cortex.tools': 'Outils IA',
    'cortex.settings': 'Paramètres IA',
    'cortex.analytics': 'Analytique IA',
    'notifications.title': 'Notifications',
    'notifications.markRead': 'Marquer comme lu',
    'notifications.clearAll': 'Tout effacer',
    'notifications.noNew': 'Aucune nouvelle notification',
  },
  de: {
    'nav.dashboard': 'Dashboard',
    'nav.tickets': 'Tickets',
    'nav.customers': 'Kunden',
    'nav.devices': 'Geräte',
    'nav.alerts': 'Warnungen',
    'nav.reports': 'Berichte',
    'nav.settings': 'Einstellungen',
    'nav.cortex': 'Cortex KI-Zentrum',
    'common.save': 'Speichern',
    'common.cancel': 'Abbrechen',
    'common.delete': 'Löschen',
    'common.edit': 'Bearbeiten',
    'common.create': 'Erstellen',
    'common.search': 'Suchen',
    'common.filter': 'Filtern',
    'common.export': 'Exportieren',
    'common.import': 'Importieren',
    'common.loading': 'Laden...',
    'common.noData': 'Keine Daten verfügbar',
    'common.success': 'Erfolg',
    'common.error': 'Fehler',
    'common.warning': 'Warnung',
    'common.info': 'Info',
    'tickets.title': 'Tickets',
    'tickets.new': 'Neues Ticket',
    'tickets.open': 'Offen',
    'tickets.closed': 'Geschlossen',
    'tickets.pending': 'Ausstehend',
    'tickets.priority': 'Priorität',
    'tickets.assignee': 'Zugewiesen',
    'dashboard.welcome': 'Willkommen bei Vanguard',
    'dashboard.overview': 'Übersicht',
    'dashboard.recentActivity': 'Letzte Aktivität',
    'dashboard.quickActions': 'Schnellaktionen',
    'cortex.hub': 'Cortex KI-Zentrum',
    'cortex.tools': 'KI-Werkzeuge',
    'cortex.settings': 'KI-Einstellungen',
    'cortex.analytics': 'KI-Analytik',
    'notifications.title': 'Benachrichtigungen',
    'notifications.markRead': 'Als gelesen markieren',
    'notifications.clearAll': 'Alle löschen',
    'notifications.noNew': 'Keine neuen Benachrichtigungen',
  },
  pt: {
    'nav.dashboard': 'Painel',
    'nav.tickets': 'Tickets',
    'nav.customers': 'Clientes',
    'nav.devices': 'Dispositivos',
    'nav.alerts': 'Alertas',
    'nav.reports': 'Relatórios',
    'nav.settings': 'Configurações',
    'nav.cortex': 'Centro de IA Cortex',
    'common.save': 'Salvar',
    'common.cancel': 'Cancelar',
    'common.delete': 'Excluir',
    'common.edit': 'Editar',
    'common.create': 'Criar',
    'common.search': 'Pesquisar',
    'common.filter': 'Filtrar',
    'common.export': 'Exportar',
    'common.import': 'Importar',
    'common.loading': 'Carregando...',
    'common.noData': 'Nenhum dado disponível',
    'common.success': 'Sucesso',
    'common.error': 'Erro',
    'common.warning': 'Aviso',
    'common.info': 'Informação',
    'tickets.title': 'Tickets',
    'tickets.new': 'Novo Ticket',
    'tickets.open': 'Aberto',
    'tickets.closed': 'Fechado',
    'tickets.pending': 'Pendente',
    'tickets.priority': 'Prioridade',
    'tickets.assignee': 'Atribuído',
    'dashboard.welcome': 'Bem-vindo ao Vanguard',
    'dashboard.overview': 'Visão Geral',
    'dashboard.recentActivity': 'Atividade Recente',
    'dashboard.quickActions': 'Ações Rápidas',
    'cortex.hub': 'Centro de IA Cortex',
    'cortex.tools': 'Ferramentas de IA',
    'cortex.settings': 'Configurações de IA',
    'cortex.analytics': 'Análise de IA',
    'notifications.title': 'Notificações',
    'notifications.markRead': 'Marcar como Lido',
    'notifications.clearAll': 'Limpar Tudo',
    'notifications.noNew': 'Sem novas notificações',
  },
  ja: {
    'nav.dashboard': 'ダッシュボード',
    'nav.tickets': 'チケット',
    'nav.customers': '顧客',
    'nav.devices': 'デバイス',
    'nav.alerts': 'アラート',
    'nav.reports': 'レポート',
    'nav.settings': '設定',
    'nav.cortex': 'Cortex AIハブ',
    'common.save': '保存',
    'common.cancel': 'キャンセル',
    'common.delete': '削除',
    'common.edit': '編集',
    'common.create': '作成',
    'common.search': '検索',
    'common.filter': 'フィルター',
    'common.export': 'エクスポート',
    'common.import': 'インポート',
    'common.loading': '読み込み中...',
    'common.noData': 'データがありません',
    'common.success': '成功',
    'common.error': 'エラー',
    'common.warning': '警告',
    'common.info': '情報',
    'tickets.title': 'チケット',
    'tickets.new': '新規チケット',
    'tickets.open': 'オープン',
    'tickets.closed': 'クローズ',
    'tickets.pending': '保留中',
    'tickets.priority': '優先度',
    'tickets.assignee': '担当者',
    'dashboard.welcome': 'Vanguardへようこそ',
    'dashboard.overview': '概要',
    'dashboard.recentActivity': '最近のアクティビティ',
    'dashboard.quickActions': 'クイックアクション',
    'cortex.hub': 'Cortex AIハブ',
    'cortex.tools': 'AIツール',
    'cortex.settings': 'AI設定',
    'cortex.analytics': 'AI分析',
    'notifications.title': '通知',
    'notifications.markRead': '既読にする',
    'notifications.clearAll': 'すべてクリア',
    'notifications.noNew': '新しい通知はありません',
  },
  zh: {
    'nav.dashboard': '仪表板',
    'nav.tickets': '工单',
    'nav.customers': '客户',
    'nav.devices': '设备',
    'nav.alerts': '警报',
    'nav.reports': '报告',
    'nav.settings': '设置',
    'nav.cortex': 'Cortex AI中心',
    'common.save': '保存',
    'common.cancel': '取消',
    'common.delete': '删除',
    'common.edit': '编辑',
    'common.create': '创建',
    'common.search': '搜索',
    'common.filter': '筛选',
    'common.export': '导出',
    'common.import': '导入',
    'common.loading': '加载中...',
    'common.noData': '暂无数据',
    'common.success': '成功',
    'common.error': '错误',
    'common.warning': '警告',
    'common.info': '信息',
    'tickets.title': '工单',
    'tickets.new': '新建工单',
    'tickets.open': '待处理',
    'tickets.closed': '已关闭',
    'tickets.pending': '待定',
    'tickets.priority': '优先级',
    'tickets.assignee': '负责人',
    'dashboard.welcome': '欢迎使用Vanguard',
    'dashboard.overview': '概览',
    'dashboard.recentActivity': '最近活动',
    'dashboard.quickActions': '快速操作',
    'cortex.hub': 'Cortex AI中心',
    'cortex.tools': 'AI工具',
    'cortex.settings': 'AI设置',
    'cortex.analytics': 'AI分析',
    'notifications.title': '通知',
    'notifications.markRead': '标记已读',
    'notifications.clearAll': '清除全部',
    'notifications.noNew': '暂无新通知',
  },
  ko: {
    'nav.dashboard': '대시보드',
    'nav.tickets': '티켓',
    'nav.customers': '고객',
    'nav.devices': '장치',
    'nav.alerts': '알림',
    'nav.reports': '보고서',
    'nav.settings': '설정',
    'nav.cortex': 'Cortex AI 허브',
    'common.save': '저장',
    'common.cancel': '취소',
    'common.delete': '삭제',
    'common.edit': '편집',
    'common.create': '생성',
    'common.search': '검색',
    'common.filter': '필터',
    'common.export': '내보내기',
    'common.import': '가져오기',
    'common.loading': '로딩 중...',
    'common.noData': '데이터 없음',
    'common.success': '성공',
    'common.error': '오류',
    'common.warning': '경고',
    'common.info': '정보',
    'tickets.title': '티켓',
    'tickets.new': '새 티켓',
    'tickets.open': '진행 중',
    'tickets.closed': '완료',
    'tickets.pending': '대기 중',
    'tickets.priority': '우선순위',
    'tickets.assignee': '담당자',
    'dashboard.welcome': 'Vanguard에 오신 것을 환영합니다',
    'dashboard.overview': '개요',
    'dashboard.recentActivity': '최근 활동',
    'dashboard.quickActions': '빠른 작업',
    'cortex.hub': 'Cortex AI 허브',
    'cortex.tools': 'AI 도구',
    'cortex.settings': 'AI 설정',
    'cortex.analytics': 'AI 분석',
    'notifications.title': '알림',
    'notifications.markRead': '읽음으로 표시',
    'notifications.clearAll': '모두 지우기',
    'notifications.noNew': '새 알림 없음',
  },
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguage] = useState<Language>(() => {
    const saved = localStorage.getItem('vanguard_language');
    return (saved as Language) || 'en';
  });

  useEffect(() => {
    localStorage.setItem('vanguard_language', language);
    document.documentElement.lang = language;
  }, [language]);

  const t = (key: string): string => {
    return translations[language]?.[key] || translations['en']?.[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t, languages }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}
