import { useState, useEffect } from 'react';
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Badge } from '@/components/ui/badge';
import { Input } from '@/components/ui/input';
import { Textarea } from '@/components/ui/textarea';
import { ScrollArea } from '@/components/ui/scroll-area';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select';
import { Tabs, TabsContent, TabsList, TabsTrigger } from '@/components/ui/tabs';
import { 
  Wand2, FileText, Sparkles, Eye, Edit, Save, 
  Send, Clock, CheckCircle2, Tag, Folder, Loader2
} from 'lucide-react';
import { toast } from 'sonner';
import { supabase } from '@/integrations/supabase/client';

interface KBDraft {
  id: string;
  title: string;
  category: string;
  status: 'draft' | 'review' | 'published';
  generatedFrom: string;
  createdAt: string;
  content: string;
  tags: string[];
}

const CATEGORIES = [
  'Email & Collaboration',
  'Network & Security',
  'Hardware & Devices',
  'Cloud Services',
  'Operating Systems',
  'Applications'
];

export function KBArticleGenerator() {
  const [drafts, setDrafts] = useState<KBDraft[]>([]);
  const [selectedDraft, setSelectedDraft] = useState<KBDraft | null>(null);
  const [isGenerating, setIsGenerating] = useState(false);
  const [editMode, setEditMode] = useState(false);
  const [editContent, setEditContent] = useState('');
  const [isLoading, setIsLoading] = useState(true);

  useEffect(() => {
    loadDrafts();
  }, []);

  const loadDrafts = async () => {
    try {
      const { data: { user } } = await supabase.auth.getUser();
      if (!user) return;

      const { data, error } = await supabase
        .from('vanguard_kb_drafts')
        .select('*')
        .eq('user_id', user.id)
        .order('created_at', { ascending: false });

      if (error) throw error;

      const mappedDrafts = (data || []).map((d: any) => ({
        id: d.id,
        title: d.title,
        category: d.category,
        status: d.status as 'draft' | 'review' | 'published',
        generatedFrom: d.generated_from || '',
        createdAt: new Date(d.created_at).toISOString().split('T')[0],
        content: d.content,
        tags: d.tags || []
      }));

      setDrafts(mappedDrafts);
      if (mappedDrafts.length > 0) {
        setSelectedDraft(mappedDrafts[0]);
        setEditContent(mappedDrafts[0].content);
      }
    } catch (error) {
      console.error('Error loading drafts:', error);
    } finally {
      setIsLoading(false);
    }
  };

  const handleGenerate = async () => {
    setIsGenerating(true);
    
    try {
      const { data: { user } } = await supabase.auth.getUser();
      if (!user) throw new Error('Not authenticated');

      // Generate a new draft
      const newDraft = {
        user_id: user.id,
        title: 'New Generated Article',
        category: 'General',
        status: 'draft',
        generated_from: 'AI Pattern Detection',
        content: `# New Generated Article

## Overview
This article was generated from detected patterns.

## Content
Add your content here...

## Resolution Steps
1. Step one
2. Step two
3. Step three

---
*Generated by Vanguard Cortex AI*`,
        tags: ['auto-generated']
      };

      const { data, error } = await supabase
        .from('vanguard_kb_drafts')
        .insert(newDraft)
        .select()
        .single();

      if (error) throw error;

      const mapped: KBDraft = {
        id: data.id,
        title: data.title,
        category: data.category,
        status: data.status as 'draft' | 'review' | 'published',
        generatedFrom: data.generated_from || '',
        createdAt: new Date(data.created_at).toISOString().split('T')[0],
        content: data.content,
        tags: data.tags || []
      };

      setDrafts([mapped, ...drafts]);
      setSelectedDraft(mapped);
      setEditContent(mapped.content);
      toast.success('KB article draft generated');
    } catch (error) {
      console.error('Error generating:', error);
      toast.error('Failed to generate article');
    } finally {
      setIsGenerating(false);
    }
  };

  const handleSave = async () => {
    if (!selectedDraft) return;

    try {
      await supabase
        .from('vanguard_kb_drafts')
        .update({ content: editContent })
        .eq('id', selectedDraft.id);

      setDrafts(drafts.map(d => 
        d.id === selectedDraft.id ? { ...d, content: editContent } : d
      ));
      setSelectedDraft({ ...selectedDraft, content: editContent });
      setEditMode(false);
      toast.success('Draft saved');
    } catch (error) {
      console.error('Error saving:', error);
      toast.error('Failed to save draft');
    }
  };

  const handlePublish = async () => {
    if (!selectedDraft) return;

    try {
      const { data: { user } } = await supabase.auth.getUser();
      if (!user) throw new Error('Not authenticated');

      // Update draft status
      await supabase
        .from('vanguard_kb_drafts')
        .update({ status: 'published' })
        .eq('id', selectedDraft.id);

      // Also publish to client_portal_kb
      await supabase.from('client_portal_kb').insert({
        title: selectedDraft.title,
        content: selectedDraft.content,
        category: selectedDraft.category,
        tags: selectedDraft.tags,
        is_public: true,
        is_featured: false,
        created_by: user.id
      });

      setDrafts(drafts.map(d =>
        d.id === selectedDraft.id ? { ...d, status: 'published' } : d
      ));
      setSelectedDraft({ ...selectedDraft, status: 'published' });
      toast.success('Article published to Knowledge Base');
    } catch (error) {
      console.error('Error publishing:', error);
      toast.error('Failed to publish article');
    }
  };

  const getStatusBadge = (status: string) => {
    switch (status) {
      case 'published':
        return <Badge className="bg-green-500/20 text-green-400 border border-green-500/30">Published</Badge>;
      case 'review':
        return <Badge className="bg-amber-500/20 text-amber-400 border border-amber-500/30">In Review</Badge>;
      default:
        return <Badge className="bg-slate-500/20 text-slate-400 border border-slate-500/30">Draft</Badge>;
    }
  };

  if (isLoading) {
    return (
      <div className="flex items-center justify-center h-64">
        <Loader2 className="h-8 w-8 animate-spin text-cyan-400" />
      </div>
    );
  }

  return (
    <div className="space-y-6">
      {/* Header */}
      <div className="flex items-center justify-between">
        <div className="flex items-center gap-3">
          <div className="p-2 rounded-lg bg-cyan-500/20 border border-cyan-500/30">
            <Wand2 className="h-5 w-5 text-cyan-400" />
          </div>
          <div>
            <h2 className="text-lg font-semibold text-white">KB Article Generator</h2>
            <p className="text-sm text-slate-400">AI-powered Knowledge Base article creation from tickets</p>
          </div>
        </div>
        <Button
          onClick={handleGenerate}
          disabled={isGenerating}
          className="bg-gradient-to-r from-cyan-500 to-purple-600 hover:from-cyan-600 hover:to-purple-700"
        >
          {isGenerating ? (
            <>
              <Loader2 className="h-4 w-4 mr-2 animate-spin" />
              Generating...
            </>
          ) : (
            <>
              <Sparkles className="h-4 w-4 mr-2" />
              Generate from Patterns
            </>
          )}
        </Button>
      </div>

      <div className="grid lg:grid-cols-3 gap-6">
        {/* Drafts List */}
        <Card className="bg-black/80 border-cyan-500/30">
          <CardHeader>
            <CardTitle className="text-purple-400 text-sm">Article Drafts</CardTitle>
            <CardDescription className="text-slate-500">
              {drafts.length} articles in queue
            </CardDescription>
          </CardHeader>
          <CardContent>
            <ScrollArea className="h-[500px]">
              {drafts.length === 0 ? (
                <div className="text-center py-12 text-slate-500">
                  <FileText className="h-12 w-12 mx-auto mb-4 opacity-50" />
                  <p>No drafts yet</p>
                  <p className="text-sm">Generate your first article</p>
                </div>
              ) : (
                <div className="space-y-3">
                  {drafts.map((draft) => (
                    <div
                      key={draft.id}
                      onClick={() => {
                        setSelectedDraft(draft);
                        setEditContent(draft.content);
                        setEditMode(false);
                      }}
                      className={`p-3 rounded-lg border cursor-pointer transition-all ${
                        selectedDraft?.id === draft.id
                          ? 'bg-cyan-500/10 border-cyan-500/40'
                          : 'bg-slate-900/50 border-slate-700 hover:border-cyan-500/30'
                      }`}
                    >
                      <div className="flex items-start justify-between gap-2 mb-2">
                        <FileText className="h-4 w-4 text-cyan-400 shrink-0 mt-0.5" />
                        {getStatusBadge(draft.status)}
                      </div>
                      <p className="text-sm text-white font-medium line-clamp-2">{draft.title}</p>
                      <p className="text-xs text-slate-500 mt-1">{draft.category}</p>
                      <div className="flex items-center gap-2 mt-2 text-xs text-slate-500">
                        <Clock className="h-3 w-3" />
                        <span>{draft.createdAt}</span>
                      </div>
                    </div>
                  ))}
                </div>
              )}
            </ScrollArea>
          </CardContent>
        </Card>

        {/* Article Editor/Preview */}
        {selectedDraft ? (
          <Card className="bg-black/80 border-cyan-500/30 lg:col-span-2">
            <CardHeader>
              <div className="flex items-start justify-between">
                <div className="flex-1">
                  <div className="flex items-center gap-2 mb-2">
                    {getStatusBadge(selectedDraft.status)}
                    <Badge variant="outline" className="border-slate-600 text-slate-400">
                      <Folder className="h-3 w-3 mr-1" />
                      {selectedDraft.category}
                    </Badge>
                  </div>
                  <CardTitle className="text-white">{selectedDraft.title}</CardTitle>
                  <CardDescription className="text-slate-500 mt-1">
                    {selectedDraft.generatedFrom}
                  </CardDescription>
                </div>
              </div>
            </CardHeader>
            <CardContent className="space-y-4">
              {/* Action Buttons */}
              <div className="flex items-center gap-2">
                <Button
                  variant="outline"
                  size="sm"
                  onClick={() => {
                    setEditMode(!editMode);
                    if (!editMode) setEditContent(selectedDraft.content);
                  }}
                  className="border-cyan-500/30 text-cyan-400 hover:bg-cyan-500/10"
                >
                  {editMode ? <Eye className="h-4 w-4 mr-1" /> : <Edit className="h-4 w-4 mr-1" />}
                  {editMode ? 'Preview' : 'Edit'}
                </Button>
                {editMode && (
                  <Button
                    variant="outline"
                    size="sm"
                    onClick={handleSave}
                    className="border-green-500/30 text-green-400 hover:bg-green-500/10"
                  >
                    <Save className="h-4 w-4 mr-1" />
                    Save Draft
                  </Button>
                )}
                <Button
                  size="sm"
                  onClick={handlePublish}
                  disabled={selectedDraft.status === 'published'}
                  className="bg-gradient-to-r from-cyan-500 to-purple-600 hover:from-cyan-600 hover:to-purple-700 ml-auto"
                >
                  <Send className="h-4 w-4 mr-1" />
                  Publish
                </Button>
              </div>

              {/* Content Area */}
              <div className="border border-slate-700 rounded-lg overflow-hidden">
                {editMode ? (
                  <Textarea
                    value={editContent}
                    onChange={(e) => setEditContent(e.target.value)}
                    className="min-h-[400px] bg-slate-900/50 border-0 text-slate-300 font-mono text-sm"
                  />
                ) : (
                  <ScrollArea className="h-[400px]">
                    <div className="p-4 prose prose-invert prose-sm max-w-none">
                      <pre className="whitespace-pre-wrap text-slate-300 text-sm font-sans">
                        {selectedDraft.content}
                      </pre>
                    </div>
                  </ScrollArea>
                )}
              </div>

              {/* Tags */}
              <div className="flex items-center gap-2 flex-wrap">
                <Tag className="h-4 w-4 text-slate-500" />
                {selectedDraft.tags.map((tag) => (
                  <Badge
                    key={tag}
                    variant="outline"
                    className="border-purple-500/30 text-purple-400"
                  >
                    {tag}
                  </Badge>
                ))}
              </div>
            </CardContent>
          </Card>
        ) : (
          <Card className="bg-black/80 border-cyan-500/30 lg:col-span-2 flex items-center justify-center">
            <div className="text-center py-12">
              <FileText className="h-12 w-12 text-slate-600 mx-auto mb-4" />
              <p className="text-slate-500">Select a draft to edit or generate a new one</p>
            </div>
          </Card>
        )}
      </div>
    </div>
  );
}