# Ultrium RMM Agent GUI Installer v2.1
# Professional Windows Forms GUI Installer with System Tray Integration
# Run with: PowerShell -ExecutionPolicy Bypass -File UltriumRMMAgent-GUI-Installer.ps1

param(
    [string]$ServerUrl = "https://nsyobmjpdpvesjwdphlh.supabase.co",
    [string]$AgentToken = "",
    [string]$CompanyId = "",
    [string]$MSPId = "",
    [switch]$Silent
)

Add-Type -AssemblyName System.Windows.Forms
Add-Type -AssemblyName System.Drawing
Add-Type -AssemblyName PresentationFramework

# Configuration
$ServiceName = "UltriumRMMAgent"
$ServiceDisplayName = "Ultrium RMM Agent"
$ServiceDescription = "Ultrium Remote Monitoring and Management Agent with Live Remote Desktop"
$InstallPath = "$env:ProgramFiles\Ultrium\RMMAgent"
$ConfigFile = "$InstallPath\config.json"
$LogFile = "$InstallPath\agent.log"

# Ultrium Logo (Base64 encoded 32x32 icon for system tray)
$UltriumIconBase64 = @"
iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAYAAABzenr0AAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAAAdgAAAHYBTnsmCAAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoAAAOESURBVFiFtZdNaBNBFMefmSTbNGnapk1am1ZrW6qIFrEWxYMgeFE8eBEPevGgJ8WDF0/ePHjw4sGLBy9ePHjRi3jQg4IXD1708EGLFy9ePHjw4MGDBw8ePHjwIAhCLWJrm6RJm2y+dhJnZmdm3u/N7L+ZBQAAAAAAABDyH/H/RERERF5ERERERERERET+I+L/gaOqujzGWERERERERERERERERP8j4j8iqt9QRERERERERERERERE/iPi/wGSE0RERERERERERERERERE/iPiVlVdHiLyERERERERERERERER/4j4XVVV1eUhIh8RERERERERERERERER/4j4LQGhFREREREREREREREREf+L+E8Qh6qqysM1VdXlISIf//9ER0TEfIjIR0REREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREERE
"@

function Write-Log {
    param([string]$Message)
    $timestamp = Get-Date -Format "yyyy-MM-dd HH:mm:ss"
    Write-Host "$timestamp - $Message"
    
    # Only try to write to file if the directory exists
    try {
        $logDir = Split-Path $LogFile -Parent
        if (Test-Path $logDir) {
            "$timestamp - $Message" | Out-File -FilePath $LogFile -Append -ErrorAction SilentlyContinue
        }
    } catch {
        # Silently ignore file logging errors during early startup
    }
}

function Test-Administrator {
    $currentPrincipal = New-Object Security.Principal.WindowsPrincipal([Security.Principal.WindowsIdentity]::GetCurrent())
    return $currentPrincipal.IsInRole([Security.Principal.WindowsBuiltInRole]::Administrator)
}

function Get-SystemInfo {
    try {
        $os = Get-CimInstance -ClassName Win32_OperatingSystem
        $computer = Get-CimInstance -ClassName Win32_ComputerSystem
        $cpu = Get-CimInstance -ClassName Win32_Processor | Select-Object -First 1
        $memory = Get-CimInstance -ClassName Win32_PhysicalMemory | Measure-Object Capacity -Sum
        $network = Get-NetAdapter | Where-Object { $_.Status -eq "Up" } | Select-Object -First 1
        $ip = Get-NetIPAddress -AddressFamily IPv4 | Where-Object { $_.PrefixOrigin -eq "Dhcp" -or $_.PrefixOrigin -eq "Manual" } | Select-Object -First 1
        
        return @{
            hostname = $env:COMPUTERNAME
            ip_address = $ip.IPAddress
            os_info = "$($os.Caption) $($os.Version)"
            device_type = if ($computer.PCSystemType -eq 2) { "laptop" } else { "desktop" }
            agent_version = "2.1.0-gui"
            cpu_info = $cpu.Name
            total_memory = [math]::Round($memory.Sum / 1GB, 2)
            available_memory = [math]::Round($os.FreePhysicalMemory / 1MB, 2)
            domain = $computer.Domain
            manufacturer = $computer.Manufacturer
            model = $computer.Model
            mac_address = $network.MacAddress
            architecture = $env:PROCESSOR_ARCHITECTURE
            last_boot = $os.LastBootUpTime
        }
    } catch {
        Write-Log "Error getting system info: $($_.Exception.Message)"
        return @{}
    }
}

function Show-InstallationGUI {
    # Create the main form
    $form = New-Object System.Windows.Forms.Form
    $form.Text = "Ultrium RMM Agent Installer"
    $form.Size = New-Object System.Drawing.Size(500, 400)
    $form.StartPosition = "CenterScreen"
    $form.FormBorderStyle = [System.Windows.Forms.FormBorderStyle]::FixedDialog
    $form.MaximizeBox = $false
    $form.MinimizeBox = $false

    # Set form icon from base64
    try {
        $iconBytes = [Convert]::FromBase64String($UltriumIconBase64)
        $ms = New-Object System.IO.MemoryStream($iconBytes, 0, $iconBytes.Length)
        $form.Icon = [System.Drawing.Icon]::FromHandle(([System.Drawing.Bitmap]::new($ms)).GetHicon())
    } catch {
        Write-Log "Could not load icon: $($_.Exception.Message)"
    }

    # Logo and title
    $titleLabel = New-Object System.Windows.Forms.Label
    $titleLabel.Text = "Ultrium RMM Agent"
    $titleLabel.Font = New-Object System.Drawing.Font("Segoe UI", 16, [System.Drawing.FontStyle]::Bold)
    $titleLabel.ForeColor = [System.Drawing.Color]::FromArgb(0, 120, 215)
    $titleLabel.Location = New-Object System.Drawing.Point(20, 20)
    $titleLabel.Size = New-Object System.Drawing.Size(400, 40)
    $titleLabel.TextAlign = [System.Drawing.ContentAlignment]::MiddleCenter

    $subtitleLabel = New-Object System.Windows.Forms.Label
    $subtitleLabel.Text = "Professional Remote Monitoring & Management"
    $subtitleLabel.Font = New-Object System.Drawing.Font("Segoe UI", 10)
    $subtitleLabel.Location = New-Object System.Drawing.Point(20, 60)
    $subtitleLabel.Size = New-Object System.Drawing.Size(400, 20)
    $subtitleLabel.TextAlign = [System.Drawing.ContentAlignment]::MiddleCenter

    # Server URL field
    $serverLabel = New-Object System.Windows.Forms.Label
    $serverLabel.Text = "Server URL:"
    $serverLabel.Location = New-Object System.Drawing.Point(20, 100)
    $serverLabel.Size = New-Object System.Drawing.Size(100, 20)

    $serverTextBox = New-Object System.Windows.Forms.TextBox
    $serverTextBox.Location = New-Object System.Drawing.Point(130, 98)
    $serverTextBox.Size = New-Object System.Drawing.Size(330, 22)
    $serverTextBox.Text = $ServerUrl

    # Agent Token field
    $tokenLabel = New-Object System.Windows.Forms.Label
    $tokenLabel.Text = "Agent Token:"
    $tokenLabel.Location = New-Object System.Drawing.Point(20, 135)
    $tokenLabel.Size = New-Object System.Drawing.Size(100, 20)

    $tokenTextBox = New-Object System.Windows.Forms.TextBox
    $tokenTextBox.Location = New-Object System.Drawing.Point(130, 133)
    $tokenTextBox.Size = New-Object System.Drawing.Size(330, 22)
    $tokenTextBox.UseSystemPasswordChar = $true
    $tokenTextBox.Text = $AgentToken

    # Company ID field
    $companyLabel = New-Object System.Windows.Forms.Label
    $companyLabel.Text = "Company ID:"
    $companyLabel.Location = New-Object System.Drawing.Point(20, 170)
    $companyLabel.Size = New-Object System.Drawing.Size(100, 20)

    $companyTextBox = New-Object System.Windows.Forms.TextBox
    $companyTextBox.Location = New-Object System.Drawing.Point(130, 168)
    $companyTextBox.Size = New-Object System.Drawing.Size(330, 22)
    $companyTextBox.Text = $CompanyId

    # MSP ID field (optional)
    $mspLabel = New-Object System.Windows.Forms.Label
    $mspLabel.Text = "MSP ID (opt):"
    $mspLabel.Location = New-Object System.Drawing.Point(20, 205)
    $mspLabel.Size = New-Object System.Drawing.Size(100, 20)

    $mspTextBox = New-Object System.Windows.Forms.TextBox
    $mspTextBox.Location = New-Object System.Drawing.Point(130, 203)
    $mspTextBox.Size = New-Object System.Drawing.Size(330, 22)
    $mspTextBox.Text = $MSPId

    # Progress bar
    $progressBar = New-Object System.Windows.Forms.ProgressBar
    $progressBar.Location = New-Object System.Drawing.Point(20, 250)
    $progressBar.Size = New-Object System.Drawing.Size(440, 20)
    $progressBar.Style = [System.Windows.Forms.ProgressBarStyle]::Continuous

    # Status label
    $statusLabel = New-Object System.Windows.Forms.Label
    $statusLabel.Text = "Ready to install"
    $statusLabel.Location = New-Object System.Drawing.Point(20, 280)
    $statusLabel.Size = New-Object System.Drawing.Size(440, 20)

    # Install button
    $installButton = New-Object System.Windows.Forms.Button
    $installButton.Text = "Install Agent"
    $installButton.Location = New-Object System.Drawing.Point(280, 315)
    $installButton.Size = New-Object System.Drawing.Size(100, 30)
    $installButton.BackColor = [System.Drawing.Color]::FromArgb(0, 120, 215)
    $installButton.ForeColor = [System.Drawing.Color]::White
    $installButton.FlatStyle = [System.Windows.Forms.FlatStyle]::Flat

    # Cancel button
    $cancelButton = New-Object System.Windows.Forms.Button
    $cancelButton.Text = "Cancel"
    $cancelButton.Location = New-Object System.Drawing.Point(390, 315)
    $cancelButton.Size = New-Object System.Drawing.Size(70, 30)
    $cancelButton.DialogResult = [System.Windows.Forms.DialogResult]::Cancel

    # Add controls to form
    $form.Controls.AddRange(@(
        $titleLabel, $subtitleLabel,
        $serverLabel, $serverTextBox,
        $tokenLabel, $tokenTextBox,
        $companyLabel, $companyTextBox,
        $mspLabel, $mspTextBox,
        $progressBar, $statusLabel,
        $installButton, $cancelButton
    ))

    # Install button click event
    $installButton.Add_Click({
        if ([string]::IsNullOrWhiteSpace($tokenTextBox.Text)) {
            [System.Windows.Forms.MessageBox]::Show("Agent Token is required", "Error", [System.Windows.Forms.MessageBoxButtons]::OK, [System.Windows.Forms.MessageBoxIcon]::Error)
            return
        }

        $installButton.Enabled = $false
        $cancelButton.Enabled = $false
        $progressBar.Value = 0
        $statusLabel.Text = "Starting installation..."

        # Update progress
        $progressBar.Value = 20
        $statusLabel.Text = "Gathering system information..."
        $form.Refresh()
        Start-Sleep -Milliseconds 500

        # Get system info
        $systemInfo = Get-SystemInfo
        
        $progressBar.Value = 40
        $statusLabel.Text = "Registering with server..."
        $form.Refresh()
        Start-Sleep -Milliseconds 500

        # Register with server
        $deviceId = Register-WithServer -SystemInfo $systemInfo -Token $tokenTextBox.Text -CompanyId $companyTextBox.Text -MSPId $mspTextBox.Text -ServerUrl $serverTextBox.Text

        if ($deviceId) {
            $progressBar.Value = 60
            $statusLabel.Text = "Creating installation directory..."
            $form.Refresh()
            Start-Sleep -Milliseconds 500

            # Create installation
            $success = Install-AgentFiles -DeviceId $deviceId -Token $tokenTextBox.Text -CompanyId $companyTextBox.Text -MSPId $mspTextBox.Text -ServerUrl $serverTextBox.Text -SystemInfo $systemInfo

            if ($success) {
                $progressBar.Value = 80
                $statusLabel.Text = "Creating Windows service..."
                $form.Refresh()
                Start-Sleep -Milliseconds 500

                # Create service
                $serviceSuccess = Create-AgentService

                if ($serviceSuccess) {
                    $progressBar.Value = 100
                    $statusLabel.Text = "Installation completed successfully!"
                    $form.Refresh()
                    Start-Sleep -Milliseconds 1000

                    [System.Windows.Forms.MessageBox]::Show("Ultrium RMM Agent installed successfully!`n`nDevice ID: $deviceId`nHostname: $($systemInfo.hostname)`n`nThe agent is now running and will appear in your dashboard within 5 minutes.", "Installation Complete", [System.Windows.Forms.MessageBoxButtons]::OK, [System.Windows.Forms.MessageBoxIcon]::Information)
                    
                    # Show system tray notification
                    Show-SystemTrayIcon
                    
                    $form.DialogResult = [System.Windows.Forms.DialogResult]::OK
                    $form.Close()
                } else {
                    [System.Windows.Forms.MessageBox]::Show("Failed to create Windows service. Please check the log file at: $LogFile", "Service Creation Failed", [System.Windows.Forms.MessageBoxButtons]::OK, [System.Windows.Forms.MessageBoxIcon]::Error)
                    $installButton.Enabled = $true
                    $cancelButton.Enabled = $true
                }
            } else {
                [System.Windows.Forms.MessageBox]::Show("Failed to install agent files. Please check the log file at: $LogFile", "Installation Failed", [System.Windows.Forms.MessageBoxButtons]::OK, [System.Windows.Forms.MessageBoxIcon]::Error)
                $installButton.Enabled = $true
                $cancelButton.Enabled = $true
            }
        } else {
            [System.Windows.Forms.MessageBox]::Show("Failed to register with server. Please check your token and network connection.", "Registration Failed", [System.Windows.Forms.MessageBoxButtons]::OK, [System.Windows.Forms.MessageBoxIcon]::Error)
            $installButton.Enabled = $true
            $cancelButton.Enabled = $true
            $progressBar.Value = 0
            $statusLabel.Text = "Ready to install"
        }
    })

    # Show the form
    $result = $form.ShowDialog()
    return $result
}

function Register-WithServer {
    param(
        [hashtable]$SystemInfo,
        [string]$Token,
        [string]$CompanyId,
        [string]$MSPId,
        [string]$ServerUrl
    )
    
    $registrationData = @{
        action = "register_agent"
        hostname = $SystemInfo.hostname
        ip_address = $SystemInfo.ip_address
        os_info = $SystemInfo.os_info
        device_type = $SystemInfo.device_type
        agent_version = $SystemInfo.agent_version
        client_id = $CompanyId
        msp_id = $MSPId
        system_info = $SystemInfo
    }
    
    try {
        $headers = @{
            "Content-Type" = "application/json"
            "Authorization" = "Bearer $Token"
        }
        
        $response = Invoke-RestMethod -Uri "$ServerUrl/functions/v1/rmm-agent" -Method Post -Body ($registrationData | ConvertTo-Json -Depth 5) -Headers $headers -TimeoutSec 30
        
        if ($response.success) {
            Write-Log "Agent registered successfully. Device ID: $($response.device_id)"
            return $response.device_id
        } else {
            Write-Log "Registration failed: $($response.error)"
            return $null
        }
    } catch {
        Write-Log "Registration error: $($_.Exception.Message)"
        return $null
    }
}

function Install-AgentFiles {
    param(
        [string]$DeviceId,
        [string]$Token,
        [string]$CompanyId,
        [string]$MSPId,
        [string]$ServerUrl,
        [hashtable]$SystemInfo
    )
    
    try {
        # Create installation directory
        if (-not (Test-Path $InstallPath)) {
            New-Item -ItemType Directory -Path $InstallPath -Force | Out-Null
        }
        
        # Create configuration file
        $config = @{
            server_url = $ServerUrl
            agent_token = $Token
            company_id = $CompanyId
            msp_id = $MSPId
            device_id = $DeviceId
            heartbeat_interval = 30
            command_check_interval = 10
            install_date = (Get-Date).ToString("yyyy-MM-ddTHH:mm:ssZ")
            version = "2.1.0-gui"
            system_info = $SystemInfo
        }
        
        $config | ConvertTo-Json -Depth 4 | Out-File -FilePath $ConfigFile -Encoding UTF8
        
        # Create the service script (same as before but optimized)
        $ServiceScriptContent = @"
# Ultrium RMM Agent Service - GUI Version
`$ConfigPath = "$ConfigFile"
`$LogPath = "$LogFile"

function Write-AgentLog {
    param([string]`$Message)
    `$timestamp = Get-Date -Format "yyyy-MM-dd HH:mm:ss"
    try {
        "`$timestamp - `$Message" | Out-File -FilePath `$LogPath -Append
    } catch {}
}

function Load-Config {
    try {
        if (Test-Path `$ConfigPath) {
            return Get-Content `$ConfigPath | ConvertFrom-Json
        }
    } catch {
        Write-AgentLog "Error loading config: `$(`$_.Exception.Message)"
    }
    return `$null
}

function Send-Heartbeat {
    param([object]`$Config)
    
    try {
        `$cpu = Get-WmiObject -Class Win32_Processor | Measure-Object -Property LoadPercentage -Average
        `$memory = Get-WmiObject -Class Win32_OperatingSystem
        `$disk = Get-WmiObject -Class Win32_LogicalDisk -Filter "DriveType=3" | Select-Object -First 1
        
        `$metrics = @{
            cpu_usage = `$cpu.Average
            memory_usage = [math]::Round(((`$memory.TotalVisibleMemorySize - `$memory.FreePhysicalMemory) / `$memory.TotalVisibleMemorySize) * 100, 2)
            disk_usage = if (`$disk) { [math]::Round(((`$disk.Size - `$disk.FreeSpace) / `$disk.Size) * 100, 2) } else { 0 }
            timestamp = (Get-Date).ToString("yyyy-MM-ddTHH:mm:ssZ")
        }
        
        `$heartbeatData = @{
            action = "heartbeat"
            device_id = `$Config.device_id
            metrics = `$metrics
        }
        
        `$headers = @{
            "Content-Type" = "application/json"
            "Authorization" = "Bearer `$(`$Config.agent_token)"
        }
        
        Invoke-RestMethod -Uri "`$(`$Config.server_url)/functions/v1/rmm-agent" -Method Post -Body (`$heartbeatData | ConvertTo-Json -Depth 3) -Headers `$headers -TimeoutSec 30 | Out-Null
        Write-AgentLog "Heartbeat sent successfully"
        
    } catch {
        Write-AgentLog "Heartbeat failed: `$(`$_.Exception.Message)"
    }
}

function Check-Commands {
    param([object]`$Config)
    
    try {
        `$commandData = @{
            action = "get_commands"
            device_id = `$Config.device_id
        }
        
        `$headers = @{
            "Content-Type" = "application/json"
            "Authorization" = "Bearer `$(`$Config.agent_token)"
        }
        
        `$response = Invoke-RestMethod -Uri "`$(`$Config.server_url)/functions/v1/rmm-command" -Method Post -Body (`$commandData | ConvertTo-Json) -Headers `$headers -TimeoutSec 30
        
        if (`$response.success -and `$response.commands) {
            foreach (`$command in `$response.commands) {
                Write-AgentLog "Executing command: `$(`$command.command)"
                
                `$result = @{
                    action = "command_result"
                    command_id = `$command.id
                    success = `$false
                    output = ""
                    error = ""
                }
                
                try {
                    switch (`$command.command_type) {
                        "powershell" {
                            `$output = Invoke-Expression `$command.command 2>&1
                            `$result.success = `$true
                            `$result.output = `$output -join "`n"
                        }
                        "cmd" {
                            `$output = cmd /c `$command.command 2>&1
                            `$result.success = `$true
                            `$result.output = `$output -join "`n"
                        }
                        default {
                            `$result.error = "Unknown command type"
                        }
                    }
                } catch {
                    `$result.error = `$_.Exception.Message
                }
                
                # Send result back
                try {
                    Invoke-RestMethod -Uri "`$(`$Config.server_url)/functions/v1/rmm-command" -Method Post -Body (`$result | ConvertTo-Json -Depth 3) -Headers `$headers -TimeoutSec 30 | Out-Null
                    Write-AgentLog "Command result sent for: `$(`$command.id)"
                } catch {
                    Write-AgentLog "Failed to send command result: `$(`$_.Exception.Message)"
                }
            }
        }
        
    } catch {
        Write-AgentLog "Error checking commands: `$(`$_.Exception.Message)"
    }
}

# Main service loop
Write-AgentLog "Starting Ultrium RMM Agent v2.1 GUI..."

`$config = Load-Config
if (-not `$config) {
    Write-AgentLog "ERROR: Could not load configuration"
    exit 1
}

Write-AgentLog "Loaded configuration for device: `$(`$config.device_id)"

# Main loop
while (`$true) {
    try {
        Send-Heartbeat -Config `$config
        Check-Commands -Config `$config
        
        Start-Sleep -Seconds `$config.heartbeat_interval
        
    } catch {
        Write-AgentLog "ERROR in main loop: `$(`$_.Exception.Message)"
        Start-Sleep -Seconds 60
    }
}
"@

        $ServiceScriptPath = "$InstallPath\service.ps1"
        $ServiceScriptContent | Out-File -FilePath $ServiceScriptPath -Encoding UTF8
        
        Write-Log "Agent files created successfully"
        return $true
        
    } catch {
        Write-Log "Error creating agent files: $($_.Exception.Message)"
        return $false
    }
}

function Create-AgentService {
    try {
        $ServiceScriptPath = "$InstallPath\service.ps1"
        $servicePath = "powershell.exe -WindowStyle Hidden -ExecutionPolicy Bypass -File `"$ServiceScriptPath`""
        
        # Stop and remove existing service if it exists
        if (Get-Service -Name $ServiceName -ErrorAction SilentlyContinue) {
            Stop-Service -Name $ServiceName -Force -ErrorAction SilentlyContinue
            sc.exe delete $ServiceName | Out-Null
            Start-Sleep -Seconds 3
        }
        
        # Create new service
        New-Service -Name $ServiceName -DisplayName $ServiceDisplayName -Description $ServiceDescription -BinaryPathName $servicePath -StartupType Automatic | Out-Null
        
        # Start the service
        Start-Service -Name $ServiceName
        
        Write-Log "Service created and started successfully"
        return $true
        
    } catch {
        Write-Log "Error creating service: $($_.Exception.Message)"
        return $false
    }
}

function Show-SystemTrayIcon {
    try {
        # Create system tray icon
        Add-Type -AssemblyName System.Windows.Forms
        
        $notifyIcon = New-Object System.Windows.Forms.NotifyIcon
        
        # Set icon from base64
        try {
            $iconBytes = [Convert]::FromBase64String($UltriumIconBase64)
            $ms = New-Object System.IO.MemoryStream($iconBytes, 0, $iconBytes.Length)
            $notifyIcon.Icon = [System.Drawing.Icon]::FromHandle(([System.Drawing.Bitmap]::new($ms)).GetHicon())
        } catch {
            # Use default icon if custom icon fails
            $notifyIcon.Icon = [System.Drawing.SystemIcons]::Information
        }
        
        $notifyIcon.BalloonTipTitle = "Ultrium RMM Agent"
        $notifyIcon.BalloonTipText = "Agent installed successfully and is now monitoring this device."
        $notifyIcon.BalloonTipIcon = [System.Windows.Forms.ToolTipIcon]::Info
        $notifyIcon.Text = "Ultrium RMM Agent - Monitoring Active"
        $notifyIcon.Visible = $true
        
        # Show balloon tip
        $notifyIcon.ShowBalloonTip(5000)
        
        # Create context menu
        $contextMenu = New-Object System.Windows.Forms.ContextMenuStrip
        
        $statusItem = New-Object System.Windows.Forms.ToolStripMenuItem
        $statusItem.Text = "Agent Status: Running"
        $statusItem.Enabled = $false
        
        $separator1 = New-Object System.Windows.Forms.ToolStripSeparator
        
        $openLogsItem = New-Object System.Windows.Forms.ToolStripMenuItem
        $openLogsItem.Text = "View Logs"
        $openLogsItem.Add_Click({
            if (Test-Path $LogFile) {
                Start-Process notepad.exe $LogFile
            }
        })
        
        $configItem = New-Object System.Windows.Forms.ToolStripMenuItem
        $configItem.Text = "View Configuration"
        $configItem.Add_Click({
            if (Test-Path $ConfigFile) {
                Start-Process notepad.exe $ConfigFile
            }
        })
        
        $separator2 = New-Object System.Windows.Forms.ToolStripSeparator
        
        $exitItem = New-Object System.Windows.Forms.ToolStripMenuItem
        $exitItem.Text = "Hide Icon"
        $exitItem.Add_Click({
            $notifyIcon.Visible = $false
            $notifyIcon.Dispose()
        })
        
        $contextMenu.Items.AddRange(@($statusItem, $separator1, $openLogsItem, $configItem, $separator2, $exitItem))
        $notifyIcon.ContextMenuStrip = $contextMenu
        
        # Keep icon active for 30 seconds, then hide
        $timer = New-Object System.Windows.Forms.Timer
        $timer.Interval = 30000
        $timer.Add_Tick({
            $notifyIcon.Visible = $false
            $notifyIcon.Dispose()
            $timer.Stop()
            $timer.Dispose()
        })
        $timer.Start()
        
    } catch {
        Write-Log "Error creating system tray icon: $($_.Exception.Message)"
    }
}

function Show-UninstallGUI {
    $form = New-Object System.Windows.Forms.Form
    $form.Text = "Ultrium RMM Agent - Uninstall"
    $form.Size = New-Object System.Drawing.Size(400, 200)
    $form.StartPosition = "CenterScreen"
    $form.FormBorderStyle = [System.Windows.Forms.FormBorderStyle]::FixedDialog
    $form.MaximizeBox = $false
    $form.MinimizeBox = $false

    $label = New-Object System.Windows.Forms.Label
    $label.Text = "Are you sure you want to uninstall the Ultrium RMM Agent?"
    $label.Location = New-Object System.Drawing.Point(20, 30)
    $label.Size = New-Object System.Drawing.Size(350, 40)
    $label.TextAlign = [System.Drawing.ContentAlignment]::MiddleCenter

    $warningLabel = New-Object System.Windows.Forms.Label
    $warningLabel.Text = "This will stop monitoring and remove the agent from this device."
    $warningLabel.Location = New-Object System.Drawing.Point(20, 70)
    $warningLabel.Size = New-Object System.Drawing.Size(350, 20)
    $warningLabel.TextAlign = [System.Drawing.ContentAlignment]::MiddleCenter
    $warningLabel.ForeColor = [System.Drawing.Color]::Red

    $uninstallButton = New-Object System.Windows.Forms.Button
    $uninstallButton.Text = "Uninstall"
    $uninstallButton.Location = New-Object System.Drawing.Point(200, 120)
    $uninstallButton.Size = New-Object System.Drawing.Size(80, 30)
    $uninstallButton.BackColor = [System.Drawing.Color]::Red
    $uninstallButton.ForeColor = [System.Drawing.Color]::White
    $uninstallButton.DialogResult = [System.Windows.Forms.DialogResult]::OK

    $cancelButton = New-Object System.Windows.Forms.Button
    $cancelButton.Text = "Cancel"
    $cancelButton.Location = New-Object System.Drawing.Point(290, 120)
    $cancelButton.Size = New-Object System.Drawing.Size(80, 30)
    $cancelButton.DialogResult = [System.Windows.Forms.DialogResult]::Cancel

    $form.Controls.AddRange(@($label, $warningLabel, $uninstallButton, $cancelButton))

    return $form.ShowDialog()
}

function Uninstall-Agent {
    if (-not (Test-Administrator)) {
        [System.Windows.Forms.MessageBox]::Show("This script must be run as Administrator to uninstall the service.", "Administrator Required", [System.Windows.Forms.MessageBoxButtons]::OK, [System.Windows.Forms.MessageBoxIcon]::Error)
        exit 1
    }

    $result = Show-UninstallGUI
    if ($result -eq [System.Windows.Forms.DialogResult]::OK) {
        try {
            Write-Log "Uninstalling Ultrium RMM Agent..."
            
            # Stop and remove service
            if (Get-Service -Name $ServiceName -ErrorAction SilentlyContinue) {
                Stop-Service -Name $ServiceName -Force -ErrorAction SilentlyContinue
                sc.exe delete $ServiceName | Out-Null
                Write-Log "Service removed successfully"
            }
            
            # Remove installation directory
            if (Test-Path $InstallPath) {
                Remove-Item -Path $InstallPath -Recurse -Force
                Write-Log "Installation directory removed"
            }
            
            [System.Windows.Forms.MessageBox]::Show("Ultrium RMM Agent uninstalled successfully!", "Uninstall Complete", [System.Windows.Forms.MessageBoxButtons]::OK, [System.Windows.Forms.MessageBoxIcon]::Information)
            
        } catch {
            Write-Log "ERROR during uninstall: $($_.Exception.Message)"
            [System.Windows.Forms.MessageBox]::Show("Error during uninstall: $($_.Exception.Message)", "Uninstall Failed", [System.Windows.Forms.MessageBoxButtons]::OK, [System.Windows.Forms.MessageBoxIcon]::Error)
        }
    }
}

function Show-StatusGUI {
    $form = New-Object System.Windows.Forms.Form
    $form.Text = "Ultrium RMM Agent - Status"
    $form.Size = New-Object System.Drawing.Size(500, 350)
    $form.StartPosition = "CenterScreen"
    $form.FormBorderStyle = [System.Windows.Forms.FormBorderStyle]::FixedDialog
    $form.MaximizeBox = $false

    $service = Get-Service -Name $ServiceName -ErrorAction SilentlyContinue
    
    $statusLabel = New-Object System.Windows.Forms.Label
    if ($service) {
        $statusText = "Service Status: $($service.Status)"
        $statusColor = if ($service.Status -eq "Running") { [System.Drawing.Color]::Green } else { [System.Drawing.Color]::Red }
    } else {
        $statusText = "Service Status: Not Installed"
        $statusColor = [System.Drawing.Color]::Red
    }
    
    $statusLabel.Text = $statusText
    $statusLabel.Location = New-Object System.Drawing.Point(20, 20)
    $statusLabel.Size = New-Object System.Drawing.Size(400, 30)
    $statusLabel.Font = New-Object System.Drawing.Font("Segoe UI", 12, [System.Drawing.FontStyle]::Bold)
    $statusLabel.ForeColor = $statusColor

    $detailsText = New-Object System.Windows.Forms.TextBox
    $detailsText.Location = New-Object System.Drawing.Point(20, 60)
    $detailsText.Size = New-Object System.Drawing.Size(440, 200)
    $detailsText.Multiline = $true
    $detailsText.ScrollBars = [System.Windows.Forms.ScrollBars]::Vertical
    $detailsText.ReadOnly = $true

    $details = ""
    if (Test-Path $ConfigFile) {
        $config = Get-Content $ConfigFile | ConvertFrom-Json
        $details += "Configuration:`r`n"
        $details += "  Device ID: $($config.device_id)`r`n"
        $details += "  Server URL: $($config.server_url)`r`n"
        $details += "  Company ID: $($config.company_id)`r`n"
        $details += "  Version: $($config.version)`r`n"
        $details += "  Install Date: $($config.install_date)`r`n`r`n"
    }

    if (Test-Path $LogFile) {
        $details += "Recent Log Entries:`r`n"
        $logEntries = Get-Content $LogFile -Tail 10
        foreach ($entry in $logEntries) {
            $details += "  $entry`r`n"
        }
    }

    $detailsText.Text = $details

    $closeButton = New-Object System.Windows.Forms.Button
    $closeButton.Text = "Close"
    $closeButton.Location = New-Object System.Drawing.Point(390, 280)
    $closeButton.Size = New-Object System.Drawing.Size(70, 30)
    $closeButton.DialogResult = [System.Windows.Forms.DialogResult]::OK

    $form.Controls.AddRange(@($statusLabel, $detailsText, $closeButton))
    $form.ShowDialog() | Out-Null
}

# Main execution
try {
    if (-not $Silent) {
        if ($args.Length -eq 0) {
            # No arguments provided, show installation GUI
            $result = Show-InstallationGUI
        } elseif ($args[0] -eq "-Uninstall") {
            Uninstall-Agent
        } elseif ($args[0] -eq "-Status") {
            Show-StatusGUI
        } else {
            # Command line installation
            if (-not (Test-Administrator)) {
                [System.Windows.Forms.MessageBox]::Show("This script must be run as Administrator.", "Administrator Required", [System.Windows.Forms.MessageBoxButtons]::OK, [System.Windows.Forms.MessageBoxIcon]::Error)
                exit 1
            }
            
            if ([string]::IsNullOrWhiteSpace($AgentToken)) {
                Write-Error "AgentToken is required for installation."
                Write-Host "Usage: .\UltriumRMMAgent-GUI-Installer.ps1 -AgentToken 'your-token' -CompanyId 'your-company-id'"
                exit 1
            }
            
            # Silent installation
            $systemInfo = Get-SystemInfo
            $deviceId = Register-WithServer -SystemInfo $systemInfo -Token $AgentToken -CompanyId $CompanyId -MSPId $MSPId -ServerUrl $ServerUrl
            
            if ($deviceId) {
                $success = Install-AgentFiles -DeviceId $deviceId -Token $AgentToken -CompanyId $CompanyId -MSPId $MSPId -ServerUrl $ServerUrl -SystemInfo $systemInfo
                if ($success) {
                    $serviceSuccess = Create-AgentService
                    if ($serviceSuccess) {
                        Write-Host "Ultrium RMM Agent installed successfully!" -ForegroundColor Green
                        Write-Host "Device ID: $deviceId" -ForegroundColor Cyan
                        Show-SystemTrayIcon
                    }
                }
            }
        }
    } else {
        # Silent mode installation
        Write-Host "Running in silent mode..."
        # Implementation for silent installation
    }
} catch {
    Write-Error "An error occurred: $($_.Exception.Message)"
    Write-Log "ERROR: $($_.Exception.Message)"
    exit 1
}