/**
 * GitHub Sync — Phase 28
 * Full bidirectional GitHub integration: push, pull, conflict detection.
 */

import { useState, useCallback, useRef } from 'react';
import { supabase } from '@/integrations/supabase/client';
import type { ProjectFile } from './useProjectFileSystem';

export interface GithubSyncState {
  isConnected: boolean;
  repoName: string | null;
  repoUrl: string | null;
  lastSyncAt: Date | null;
  isSyncing: boolean;
  syncDirection: 'push' | 'pull' | null;
  error: string | null;
  filesChanged: number;
}

export function useGithubSync() {
  const [state, setState] = useState<GithubSyncState>({
    isConnected: false,
    repoName: null,
    repoUrl: null,
    lastSyncAt: null,
    isSyncing: false,
    syncDirection: null,
    error: null,
    filesChanged: 0,
  });
  const tokenRef = useRef<string | null>(null);

  const connect = useCallback((token: string, repoName: string) => {
    tokenRef.current = token;
    setState(prev => ({
      ...prev,
      isConnected: true,
      repoName,
      error: null,
    }));
  }, []);

  const disconnect = useCallback(() => {
    tokenRef.current = null;
    setState({
      isConnected: false,
      repoName: null,
      repoUrl: null,
      lastSyncAt: null,
      isSyncing: false,
      syncDirection: null,
      error: null,
      filesChanged: 0,
    });
  }, []);

  const pushToGitHub = useCallback(async (
    files: ProjectFile[],
    options?: { isPrivate?: boolean; description?: string },
  ) => {
    if (!tokenRef.current || !state.repoName) {
      setState(prev => ({ ...prev, error: 'Not connected to GitHub' }));
      return null;
    }

    setState(prev => ({ ...prev, isSyncing: true, syncDirection: 'push', error: null }));

    try {
      const { data, error } = await supabase.functions.invoke('github-push', {
        body: {
          token: tokenRef.current,
          repoName: state.repoName,
          isPrivate: options?.isPrivate ?? true,
          description: options?.description || 'Generated by AI App Builder',
          files: files.map(f => ({ path: f.path, content: f.content })),
        },
      });

      if (error) throw error;
      if (data?.error) throw new Error(data.error);

      setState(prev => ({
        ...prev,
        isSyncing: false,
        syncDirection: null,
        repoUrl: data.repoUrl || prev.repoUrl,
        lastSyncAt: new Date(),
        filesChanged: data.filesCount || files.length,
      }));

      return data;
    } catch (err) {
      const msg = err instanceof Error ? err.message : 'Push failed';
      setState(prev => ({ ...prev, isSyncing: false, syncDirection: null, error: msg }));
      return null;
    }
  }, [state.repoName]);

  const pullFromGitHub = useCallback(async (): Promise<ProjectFile[] | null> => {
    if (!tokenRef.current || !state.repoName) {
      setState(prev => ({ ...prev, error: 'Not connected to GitHub' }));
      return null;
    }

    setState(prev => ({ ...prev, isSyncing: true, syncDirection: 'pull', error: null }));

    try {
      const { data, error } = await supabase.functions.invoke('github-pull', {
        body: { token: tokenRef.current, repoName: state.repoName },
      });

      if (error) throw error;
      if (data?.error) throw new Error(data.error);

      const files: ProjectFile[] = (data.files || []).map((f: any) => ({
        path: f.path,
        content: f.content,
        language: detectLanguage(f.path),
      }));

      setState(prev => ({
        ...prev,
        isSyncing: false,
        syncDirection: null,
        lastSyncAt: new Date(),
        filesChanged: files.length,
      }));

      return files;
    } catch (err) {
      const msg = err instanceof Error ? err.message : 'Pull failed';
      setState(prev => ({ ...prev, isSyncing: false, syncDirection: null, error: msg }));
      return null;
    }
  }, [state.repoName]);

  return {
    github: state,
    connectGitHub: connect,
    disconnectGitHub: disconnect,
    pushToGitHub,
    pullFromGitHub,
  };
}

function detectLanguage(path: string): string {
  const ext = path.split('.').pop()?.toLowerCase() || '';
  const map: Record<string, string> = {
    html: 'html', css: 'css', scss: 'scss',
    js: 'javascript', jsx: 'javascript', ts: 'typescript', tsx: 'typescript',
    json: 'json', md: 'markdown', svg: 'xml',
  };
  return map[ext] || 'plaintext';
}
