import { useState, useCallback } from 'react';

export interface LogTransport {
  id: string;
  type: 'console' | 'file' | 'http' | 'supabase';
  enabled: boolean;
  config: Record<string, string>;
}

export interface LoggerConfig {
  name: string;
  level: 'trace' | 'debug' | 'info' | 'warn' | 'error' | 'fatal';
  format: 'json' | 'pretty' | 'compact';
  timestampFormat: 'iso' | 'epoch' | 'locale';
  includeContext: boolean;
  redactKeys: string[];
  transports: LogTransport[];
  sampleLogs: { level: string; message: string; data?: Record<string, unknown> }[];
}

const DEFAULT_TRANSPORTS: Omit<LogTransport, 'id'>[] = [
  { type: 'console', enabled: true, config: { colorize: 'true' } },
  { type: 'file', enabled: false, config: { path: './logs/app.log', maxSize: '10MB', maxFiles: '5' } },
  { type: 'http', enabled: false, config: { url: 'https://logs.example.com/ingest', method: 'POST' } },
  { type: 'supabase', enabled: false, config: { table: 'app_logs' } },
];

export function useStructuredLogger() {
  const [config, setConfig] = useState<LoggerConfig>({
    name: 'app-logger',
    level: 'info',
    format: 'json',
    timestampFormat: 'iso',
    includeContext: true,
    redactKeys: ['password', 'token', 'secret', 'authorization'],
    transports: DEFAULT_TRANSPORTS.map(t => ({ ...t, id: crypto.randomUUID() })),
    sampleLogs: [
      { level: 'info', message: 'Server started', data: { port: 3000 } },
      { level: 'warn', message: 'Rate limit approaching', data: { current: 95, max: 100 } },
      { level: 'error', message: 'Database connection failed', data: { host: 'db.example.com', error: 'ECONNREFUSED' } },
    ],
  });

  const addTransport = useCallback((type: LogTransport['type']) => {
    setConfig(prev => ({
      ...prev,
      transports: [...prev.transports, { id: crypto.randomUUID(), type, enabled: true, config: {} }],
    }));
  }, []);

  const removeTransport = useCallback((id: string) => {
    setConfig(prev => ({ ...prev, transports: prev.transports.filter(t => t.id !== id) }));
  }, []);

  const toggleTransport = useCallback((id: string) => {
    setConfig(prev => ({ ...prev, transports: prev.transports.map(t => t.id === id ? { ...t, enabled: !t.enabled } : t) }));
  }, []);

  const addRedactKey = useCallback((key: string) => {
    setConfig(prev => ({ ...prev, redactKeys: [...new Set([...prev.redactKeys, key])] }));
  }, []);

  const removeRedactKey = useCallback((key: string) => {
    setConfig(prev => ({ ...prev, redactKeys: prev.redactKeys.filter(k => k !== key) }));
  }, []);

  const generateCode = useCallback((): string => {
    const c = config;
    const lines: string[] = [];
    lines.push(`// ${c.name} - Structured Logger`);
    lines.push(`// Generated by AI App Builder`);
    lines.push(``);
    lines.push(`type LogLevel = 'trace' | 'debug' | 'info' | 'warn' | 'error' | 'fatal';`);
    lines.push(``);
    lines.push(`const LOG_LEVELS: Record<LogLevel, number> = {`);
    lines.push(`  trace: 10, debug: 20, info: 30, warn: 40, error: 50, fatal: 60`);
    lines.push(`};`);
    lines.push(``);
    lines.push(`const REDACT_KEYS = new Set(${JSON.stringify(c.redactKeys)});`);
    lines.push(``);
    lines.push(`function redact(obj: Record<string, unknown>): Record<string, unknown> {`);
    lines.push(`  const result: Record<string, unknown> = {};`);
    lines.push(`  for (const [key, value] of Object.entries(obj)) {`);
    lines.push(`    result[key] = REDACT_KEYS.has(key.toLowerCase()) ? '[REDACTED]' : value;`);
    lines.push(`  }`);
    lines.push(`  return result;`);
    lines.push(`}`);
    lines.push(``);
    lines.push(`function formatTimestamp(): string {`);
    if (c.timestampFormat === 'iso') lines.push(`  return new Date().toISOString();`);
    else if (c.timestampFormat === 'epoch') lines.push(`  return String(Date.now());`);
    else lines.push(`  return new Date().toLocaleString();`);
    lines.push(`}`);
    lines.push(``);
    lines.push(`class Logger {`);
    lines.push(`  private minLevel: number;`);
    lines.push(`  private name: string;`);
    lines.push(``);
    lines.push(`  constructor(name: string, level: LogLevel = '${c.level}') {`);
    lines.push(`    this.name = name;`);
    lines.push(`    this.minLevel = LOG_LEVELS[level];`);
    lines.push(`  }`);
    lines.push(``);
    lines.push(`  private log(level: LogLevel, message: string, data?: Record<string, unknown>) {`);
    lines.push(`    if (LOG_LEVELS[level] < this.minLevel) return;`);
    lines.push(`    const entry = {`);
    lines.push(`      timestamp: formatTimestamp(),`);
    lines.push(`      level,`);
    lines.push(`      logger: this.name,`);
    lines.push(`      message,`);
    lines.push(`      ...(data ? { data: redact(data) } : {}),`);
    lines.push(`    };`);
    if (c.format === 'json') {
      lines.push(`    const output = JSON.stringify(entry);`);
    } else if (c.format === 'pretty') {
      lines.push(`    const output = \`[\${entry.timestamp}] \${entry.level.toUpperCase().padEnd(5)} \${entry.message}\${data ? ' ' + JSON.stringify(entry.data, null, 2) : ''}\`;`);
    } else {
      lines.push(`    const output = \`\${entry.timestamp} \${entry.level} \${entry.message}\`;`);
    }
    // Transports
    c.transports.filter(t => t.enabled).forEach(t => {
      if (t.type === 'console') {
        lines.push(`    const consoleFn = level === 'error' || level === 'fatal' ? console.error : level === 'warn' ? console.warn : console.log;`);
        lines.push(`    consoleFn(output);`);
      } else if (t.type === 'http') {
        lines.push(`    fetch('${t.config.url || '/api/logs'}', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(entry) }).catch(() => {});`);
      }
    });
    lines.push(`  }`);
    lines.push(``);
    ['trace', 'debug', 'info', 'warn', 'error', 'fatal'].forEach(l => {
      lines.push(`  ${l}(message: string, data?: Record<string, unknown>) { this.log('${l}', message, data); }`);
    });
    lines.push(``);
    lines.push(`  child(name: string): Logger { return new Logger(\`\${this.name}:\${name}\`, '${c.level}'); }`);
    lines.push(`}`);
    lines.push(``);
    lines.push(`export const logger = new Logger('${c.name}', '${c.level}');`);
    return lines.join('\n');
  }, [config]);

  const previewLog = useCallback((log: typeof config.sampleLogs[0]): string => {
    const entry = {
      timestamp: new Date().toISOString(),
      level: log.level,
      logger: config.name,
      message: log.message,
      ...(log.data ? { data: log.data } : {}),
    };
    if (config.format === 'json') return JSON.stringify(entry, null, 2);
    if (config.format === 'pretty') return `[${entry.timestamp}] ${entry.level.toUpperCase().padEnd(5)} ${entry.message}${log.data ? ' ' + JSON.stringify(entry.data) : ''}`;
    return `${entry.timestamp} ${entry.level} ${entry.message}`;
  }, [config]);

  return { config, setConfig, addTransport, removeTransport, toggleTransport, addRedactKey, removeRedactKey, generateCode, previewLog };
}
