import { useState } from "react";
import { Button } from "@/components/ui/button";
import {
  DropdownMenu,
  DropdownMenuContent,
  DropdownMenuItem,
  DropdownMenuSeparator,
  DropdownMenuTrigger,
} from "@/components/ui/dropdown-menu";
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogTitle,
} from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Badge } from "@/components/ui/badge";
import { Download, FileText, Copy, Mail, Check, Loader2, FileType, Lock, Crown } from "lucide-react";
import { useToast } from "@/hooks/use-toast";
import { useSubscription } from "@/hooks/useSubscription";
import jsPDF from "jspdf";

interface EnhancedDocumentExportProps {
  content: string;
  title?: string;
  gptName?: string;
  category?: string;
  onExport?: (type: 'pdf' | 'copy' | 'email' | 'docx') => void;
}

type ExportFormat = 'copy' | 'pdf' | 'docx' | 'email';

const EnhancedDocumentExport = ({ 
  content, 
  title = "Generated Document",
  gptName = "AI Assistant",
  category,
  onExport 
}: EnhancedDocumentExportProps) => {
  const { toast } = useToast();
  const { subscription, createCheckout } = useSubscription();
  const [copied, setCopied] = useState(false);
  const [isGeneratingPDF, setIsGeneratingPDF] = useState(false);
  const [isGeneratingDocx, setIsGeneratingDocx] = useState(false);
  const [emailDialogOpen, setEmailDialogOpen] = useState(false);
  const [emailAddress, setEmailAddress] = useState("");
  const [isSendingEmail, setIsSendingEmail] = useState(false);

  // Determine available export formats based on tier
  const getAvailableFormats = (): ExportFormat[] => {
    const tier = subscription.subscription_tier?.toLowerCase() || 'free';
    switch (tier) {
      case "free":
        return ['copy'];
      case "starter":
        return ['copy', 'pdf'];
      case "premium":
      case "professional":
      case "enterprise":
        return ['copy', 'pdf', 'docx', 'email'];
      default:
        return ['copy'];
    }
  };

  const availableFormats = getAvailableFormats();
  const isPremiumFormat = (format: ExportFormat) => !availableFormats.includes(format);

  const handleCopyToClipboard = async () => {
    try {
      await navigator.clipboard.writeText(content);
      setCopied(true);
      toast({
        title: "Copied!",
        description: "Document copied to clipboard",
      });
      onExport?.('copy');
      setTimeout(() => setCopied(false), 2000);
    } catch (error) {
      toast({
        title: "Copy failed",
        description: "Could not copy to clipboard",
        variant: "destructive",
      });
    }
  };

  const handleDownloadPDF = async () => {
    if (isPremiumFormat('pdf')) {
      toast({
        title: "Upgrade Required",
        description: "PDF export is available on Starter plan and above",
        variant: "destructive",
      });
      return;
    }

    setIsGeneratingPDF(true);
    try {
      const doc = new jsPDF();
      const pageWidth = doc.internal.pageSize.getWidth();
      const pageHeight = doc.internal.pageSize.getHeight();
      const margin = 20;
      const lineHeight = 7;
      const maxWidth = pageWidth - margin * 2;
      
      // Header
      doc.setFillColor(124, 58, 237);
      doc.rect(0, 0, pageWidth, 35, 'F');
      
      doc.setTextColor(255, 255, 255);
      doc.setFontSize(18);
      doc.setFont('helvetica', 'bold');
      doc.text(title, margin, 22);
      
      doc.setFontSize(10);
      doc.setFont('helvetica', 'normal');
      doc.text(`Generated by ${gptName}${category ? ` • ${category}` : ''}`, margin, 30);
      
      // Metadata
      doc.setTextColor(128, 128, 128);
      doc.setFontSize(9);
      doc.text(`Date: ${new Date().toLocaleDateString()} | Time: ${new Date().toLocaleTimeString()}`, margin, 45);
      
      // Content
      doc.setTextColor(0, 0, 0);
      doc.setFontSize(11);
      doc.setFont('helvetica', 'normal');
      
      let yPos = 55;
      const lines = doc.splitTextToSize(content, maxWidth);
      
      for (const line of lines) {
        if (yPos > pageHeight - margin) {
          doc.addPage();
          yPos = margin;
        }
        doc.text(line, margin, yPos);
        yPos += lineHeight;
      }
      
      // Footer on each page
      const pageCount = doc.internal.pages.length - 1;
      for (let i = 1; i <= pageCount; i++) {
        doc.setPage(i);
        doc.setFontSize(8);
        doc.setTextColor(128, 128, 128);
        doc.text(
          `Page ${i} of ${pageCount} | Generated by UltriumAI`,
          pageWidth / 2,
          pageHeight - 10,
          { align: 'center' }
        );
      }
      
      const fileName = `${title.replace(/[^a-z0-9]/gi, '-').toLowerCase()}-${new Date().toISOString().split('T')[0]}.pdf`;
      doc.save(fileName);
      
      toast({
        title: "PDF Downloaded",
        description: `${fileName} has been saved`,
      });
      onExport?.('pdf');
    } catch (error) {
      console.error('PDF generation error:', error);
      toast({
        title: "PDF generation failed",
        description: "Could not generate PDF",
        variant: "destructive",
      });
    } finally {
      setIsGeneratingPDF(false);
    }
  };

  const handleDownloadDocx = async () => {
    if (isPremiumFormat('docx')) {
      toast({
        title: "Upgrade Required",
        description: "Word document export is available on Professional plan and above",
        variant: "destructive",
      });
      return;
    }

    setIsGeneratingDocx(true);
    try {
      // Create a simple HTML-based Word document
      const htmlContent = `
        <html xmlns:o='urn:schemas-microsoft-com:office:office' 
              xmlns:w='urn:schemas-microsoft-com:office:word'
              xmlns='http://www.w3.org/TR/REC-html40'>
        <head>
          <meta charset="utf-8">
          <title>${title}</title>
          <style>
            body { font-family: Calibri, Arial, sans-serif; font-size: 12pt; line-height: 1.5; margin: 1in; }
            h1 { color: #7c3aed; font-size: 24pt; margin-bottom: 10px; }
            .metadata { color: #666; font-size: 10pt; margin-bottom: 20px; border-bottom: 1px solid #ddd; padding-bottom: 10px; }
            .content { white-space: pre-wrap; }
            .footer { margin-top: 30px; padding-top: 10px; border-top: 1px solid #ddd; color: #888; font-size: 9pt; text-align: center; }
          </style>
        </head>
        <body>
          <h1>${title}</h1>
          <div class="metadata">
            Generated by ${gptName}${category ? ` • ${category}` : ''}<br>
            Date: ${new Date().toLocaleDateString()} | Time: ${new Date().toLocaleTimeString()}
          </div>
          <div class="content">${content.replace(/\n/g, '<br>').replace(/```(\w+)?\n([\s\S]*?)```/g, '<pre style="background:#f4f4f4;padding:10px;border-radius:5px;font-family:Consolas,monospace;">$2</pre>')}</div>
          <div class="footer">Generated by UltriumAI</div>
        </body>
        </html>
      `;
      
      const blob = new Blob([htmlContent], { type: 'application/msword' });
      const url = URL.createObjectURL(blob);
      const link = document.createElement('a');
      link.href = url;
      link.download = `${title.replace(/[^a-z0-9]/gi, '-').toLowerCase()}-${new Date().toISOString().split('T')[0]}.doc`;
      document.body.appendChild(link);
      link.click();
      document.body.removeChild(link);
      URL.revokeObjectURL(url);
      
      toast({
        title: "Document Downloaded",
        description: `Word document has been saved`,
      });
      onExport?.('docx');
    } catch (error) {
      console.error('DOCX generation error:', error);
      toast({
        title: "Document generation failed",
        description: "Could not generate Word document",
        variant: "destructive",
      });
    } finally {
      setIsGeneratingDocx(false);
    }
  };

  const handleSendEmail = async () => {
    if (isPremiumFormat('email')) {
      toast({
        title: "Upgrade Required",
        description: "Email export is available on Professional plan and above",
        variant: "destructive",
      });
      return;
    }

    if (!emailAddress) {
      toast({
        title: "Email required",
        description: "Please enter an email address",
        variant: "destructive",
      });
      return;
    }

    setIsSendingEmail(true);
    try {
      const subject = encodeURIComponent(title);
      const body = encodeURIComponent(`${title}\n\nGenerated by ${gptName} on ${new Date().toLocaleDateString()}\n\n---\n\n${content}\n\n---\nPowered by UltriumAI`);
      
      window.open(`mailto:${emailAddress}?subject=${subject}&body=${body}`, '_blank');
      
      toast({
        title: "Email prepared",
        description: "Your email client has been opened with the document",
      });
      onExport?.('email');
      setEmailDialogOpen(false);
    } catch (error) {
      toast({
        title: "Email failed",
        description: "Could not prepare email",
        variant: "destructive",
      });
    } finally {
      setIsSendingEmail(false);
    }
  };

  const renderMenuItem = (format: ExportFormat, label: string, icon: React.ReactNode, onClick: () => void, loading?: boolean) => {
    const locked = isPremiumFormat(format);
    
    return (
      <DropdownMenuItem 
        onClick={locked ? () => createCheckout('professional', 'monthly') : onClick} 
        disabled={loading}
        className={locked ? 'opacity-60' : ''}
      >
        {loading ? (
          <Loader2 className="h-4 w-4 mr-2 animate-spin" />
        ) : (
          icon
        )}
        {label}
        {locked && (
          <Badge variant="outline" className="ml-auto text-[10px] h-5">
            <Crown className="h-2.5 w-2.5 mr-1" />
            Pro
          </Badge>
        )}
      </DropdownMenuItem>
    );
  };

  return (
    <>
      <DropdownMenu>
        <DropdownMenuTrigger asChild>
          <Button variant="outline" size="sm" className="gap-2">
            <Download className="h-4 w-4" />
            Export
          </Button>
        </DropdownMenuTrigger>
        <DropdownMenuContent align="end" className="w-56">
          {renderMenuItem(
            'copy',
            copied ? 'Copied!' : 'Copy to Clipboard',
            copied ? <Check className="h-4 w-4 mr-2 text-green-500" /> : <Copy className="h-4 w-4 mr-2" />,
            handleCopyToClipboard
          )}
          <DropdownMenuSeparator />
          {renderMenuItem(
            'pdf',
            'Download as PDF',
            <FileText className="h-4 w-4 mr-2" />,
            handleDownloadPDF,
            isGeneratingPDF
          )}
          {renderMenuItem(
            'docx',
            'Download as Word',
            <FileType className="h-4 w-4 mr-2" />,
            handleDownloadDocx,
            isGeneratingDocx
          )}
          <DropdownMenuSeparator />
          {renderMenuItem(
            'email',
            'Send via Email',
            <Mail className="h-4 w-4 mr-2" />,
            () => setEmailDialogOpen(true)
          )}
        </DropdownMenuContent>
      </DropdownMenu>

      <Dialog open={emailDialogOpen} onOpenChange={setEmailDialogOpen}>
        <DialogContent>
          <DialogHeader>
            <DialogTitle>Send Document via Email</DialogTitle>
            <DialogDescription>
              Enter the recipient's email address to send this document.
            </DialogDescription>
          </DialogHeader>
          <div className="space-y-4 py-4">
            <div className="space-y-2">
              <Label htmlFor="email">Email Address</Label>
              <Input
                id="email"
                type="email"
                placeholder="recipient@example.com"
                value={emailAddress}
                onChange={(e) => setEmailAddress(e.target.value)}
              />
            </div>
            <div className="p-3 bg-muted rounded-lg">
              <p className="text-sm text-muted-foreground">
                <strong>Document:</strong> {title}
              </p>
              <p className="text-sm text-muted-foreground mt-1">
                <strong>Length:</strong> {content.length} characters
              </p>
            </div>
          </div>
          <DialogFooter>
            <Button variant="outline" onClick={() => setEmailDialogOpen(false)}>
              Cancel
            </Button>
            <Button onClick={handleSendEmail} disabled={isSendingEmail}>
              {isSendingEmail ? (
                <>
                  <Loader2 className="h-4 w-4 mr-2 animate-spin" />
                  Sending...
                </>
              ) : (
                <>
                  <Mail className="h-4 w-4 mr-2" />
                  Send Email
                </>
              )}
            </Button>
          </DialogFooter>
        </DialogContent>
      </Dialog>
    </>
  );
};

export default EnhancedDocumentExport;
