/**
 * Generate a PowerShell installer script that downloads and runs the MSI
 * with embedded credentials for zero-config deployment.
 */

interface MsiInstallerOptions {
  userId: string;
  secretKey: string;
  clientId?: string;
  clientName?: string;
  enableTray?: boolean;
}

// MSI download URL from Supabase Storage
const MSI_DOWNLOAD_URL = 'https://nsyobmjpdpvesjwdphlh.supabase.co/storage/v1/object/public/vanguard-agents/VanguardAgent.msi';

/**
 * Generate a PowerShell script that downloads and installs the MSI with pre-configured credentials
 */
export function generateMsiInstallerScript(options: MsiInstallerOptions): string {
  const { userId, secretKey, clientId, clientName, enableTray = true } = options;
  
  const escapedClientName = clientName || 'Direct Install';
  const escapedUserId = userId.replace(/"/g, '""');
  const escapedSecretKey = secretKey.replace(/"/g, '""');
  const escapedClientId = clientId?.replace(/"/g, '""') || '';
  const enableTrayValue = enableTray ? '1' : '0';
  
  // Use array join to avoid template literal issues with PowerShell syntax
  const lines = [
    '#Requires -RunAsAdministrator',
    '# =============================================================================',
    '# Ultrium Vanguard Agent MSI Installer',
    `# Pre-configured for: ${escapedClientName}`,
    '# =============================================================================',
    '# Run as Administrator: powershell -ExecutionPolicy Bypass -File Install-VanguardAgent.ps1',
    '# =============================================================================',
    '',
    '$ErrorActionPreference = "Stop"',
    '$ProgressPreference = "SilentlyContinue"',
    '',
    '# Embedded configuration (generated by Vanguard dashboard)',
    '$CONFIG = @{',
    `    UserId = "${escapedUserId}"`,
    `    SecretKey = "${escapedSecretKey}"`,
    `    ClientId = "${escapedClientId}"`,
    `    ClientName = "${escapedClientName}"`,
    `    EnableTray = "${enableTrayValue}"`,
    `    MsiUrl = "${MSI_DOWNLOAD_URL}"`,
    '}',
    '',
    'function Write-Banner {',
    '    Write-Host ""',
    '    Write-Host "  VANGUARD AGENT INSTALLER" -ForegroundColor Cyan',
    '    Write-Host "  Enterprise RMM Agent" -ForegroundColor White',
    '    if ($CONFIG.ClientName -and $CONFIG.ClientName -ne "Direct Install") {',
    '        Write-Host "  Pre-configured for: $($CONFIG.ClientName)" -ForegroundColor Yellow',
    '    }',
    '    Write-Host ""',
    '}',
    '',
    'function Download-Msi {',
    '    param([string]$Url, [string]$Destination)',
    '    ',
    '    Write-Host "[1/3] Downloading Vanguard Agent MSI..." -ForegroundColor Yellow',
    '    ',
    '    try {',
    '        [Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12',
    '        ',
    '        $webClient = New-Object System.Net.WebClient',
    '        $webClient.DownloadFile($Url, $Destination)',
    '        ',
    '        if (Test-Path $Destination) {',
    '            $size = (Get-Item $Destination).Length / 1MB',
    '            Write-Host "   Downloaded: $([math]::Round($size, 1)) MB" -ForegroundColor Green',
    '            return $true',
    '        }',
    '    }',
    '    catch {',
    '        Write-Host "   Download failed: $_" -ForegroundColor Red',
    '        return $false',
    '    }',
    '    ',
    '    return $false',
    '}',
    '',
    'function Install-Agent {',
    '    param([string]$MsiPath)',
    '    ',
    '    Write-Host "[2/3] Installing Vanguard Agent..." -ForegroundColor Yellow',
    '    ',
    '    # Build MSI arguments with embedded credentials',
    '    $msiArgs = "/i `"$MsiPath`" /qn /norestart USERID=`"$($CONFIG.UserId)`" SECRETKEY=`"$($CONFIG.SecretKey)`" ENABLETRAY=`"$($CONFIG.EnableTray)`""',
    '    ',
    '    if ($CONFIG.ClientId) {',
    '        $msiArgs += " CLIENTID=`"$($CONFIG.ClientId)`""',
    '    }',
    '    ',
    '    # Run MSI installer',
    '    $process = Start-Process -FilePath "msiexec.exe" -ArgumentList $msiArgs -Wait -PassThru',
    '    ',
    '    if ($process.ExitCode -eq 0) {',
    '        Write-Host "   Installation successful!" -ForegroundColor Green',
    '        return $true',
    '    }',
    '    elseif ($process.ExitCode -eq 3010) {',
    '        Write-Host "   Installation successful (reboot required)" -ForegroundColor Yellow',
    '        return $true',
    '    }',
    '    else {',
    '        Write-Host "   Installation failed with exit code: $($process.ExitCode)" -ForegroundColor Red',
    '        return $false',
    '    }',
    '}',
    '',
    'function Verify-Installation {',
    '    Write-Host "[3/3] Verifying installation..." -ForegroundColor Yellow',
    '    ',
    '    Start-Sleep -Seconds 3',
    '    ',
    '    $service = Get-Service -Name "VanguardAgent" -ErrorAction SilentlyContinue',
    '    ',
    '    if ($service) {',
    '        $statusColor = if ($service.Status -eq \'Running\') { \'Green\' } else { \'Yellow\' }',
    '        Write-Host "   Service Status: $($service.Status)" -ForegroundColor $statusColor',
    '        return $true',
    '    }',
    '    else {',
    '        Write-Host "   Service not found!" -ForegroundColor Red',
    '        return $false',
    '    }',
    '}',
    '',
    'function Show-Summary {',
    '    param([bool]$Success)',
    '    ',
    '    Write-Host ""',
    '    if ($Success) {',
    '        Write-Host "============================================" -ForegroundColor Green',
    '        Write-Host "  Installation Complete!" -ForegroundColor Green',
    '        Write-Host "============================================" -ForegroundColor Green',
    '        Write-Host ""',
    '        Write-Host "  The agent is now monitoring this device." -ForegroundColor White',
    '        Write-Host "  Dashboard: https://ultriumai.com/vanguard" -ForegroundColor Cyan',
    '        Write-Host ""',
    '    }',
    '    else {',
    '        Write-Host "============================================" -ForegroundColor Red',
    '        Write-Host "  Installation Failed" -ForegroundColor Red',
    '        Write-Host "============================================" -ForegroundColor Red',
    '        Write-Host ""',
    '        Write-Host "  Check Event Viewer > Windows Logs > Application" -ForegroundColor Yellow',
    '    }',
    '    Write-Host ""',
    '}',
    '',
    '# =============================================================================',
    '# Main Execution',
    '# =============================================================================',
    '',
    'Write-Banner',
    '',
    '# Create temp directory for download',
    '$tempDir = Join-Path $env:TEMP "VanguardInstall"',
    'New-Item -ItemType Directory -Path $tempDir -Force | Out-Null',
    '$msiPath = Join-Path $tempDir "VanguardAgent.msi"',
    '',
    'try {',
    '    # Download MSI',
    '    $downloaded = Download-Msi -Url $CONFIG.MsiUrl -Destination $msiPath',
    '    if (-not $downloaded) {',
    '        throw "Failed to download MSI"',
    '    }',
    '    ',
    '    # Install',
    '    $installed = Install-Agent -MsiPath $msiPath',
    '    if (-not $installed) {',
    '        throw "MSI installation failed"',
    '    }',
    '    ',
    '    # Verify',
    '    $verified = Verify-Installation',
    '    ',
    '    Show-Summary -Success $verified',
    '}',
    'catch {',
    '    Write-Host ""',
    '    Write-Host "ERROR: $_" -ForegroundColor Red',
    '    Show-Summary -Success $false',
    '    exit 1',
    '}',
    'finally {',
    '    # Cleanup temp files',
    '    if (Test-Path $tempDir) {',
    '        Remove-Item -Path $tempDir -Recurse -Force -ErrorAction SilentlyContinue',
    '    }',
    '}',
  ];

  return lines.join('\n');
}

/**
 * Generate installer script as a downloadable blob
 */
export function generateMsiInstallerBlob(options: MsiInstallerOptions): Blob {
  const script = generateMsiInstallerScript(options);
  return new Blob([script], { type: 'application/octet-stream' });
}

/**
 * Generate a simple one-liner for copy-paste deployment
 */
export function generateMsiOneLiner(options: MsiInstallerOptions): string {
  const { userId, secretKey, clientId, enableTray = true } = options;
  
  const params = [
    `USERID="${userId}"`,
    `SECRETKEY="${secretKey}"`,
    `ENABLETRAY="${enableTray ? '1' : '0'}"`,
  ];
  
  if (clientId) {
    params.push(`CLIENTID="${clientId}"`);
  }
  
  return `# Run in elevated PowerShell:
$msi = "$env:TEMP\\VanguardAgent.msi"
Invoke-WebRequest -Uri "${MSI_DOWNLOAD_URL}" -OutFile $msi
msiexec /i $msi /qn ${params.join(' ')}`;
}
