/**
 * Microsoft 365 remediation catalog — identity, session and mail actions
 * executed via the `ms-graph-remediate` edge function.
 */
import type { Remediation } from './types';

export const MS365_REMEDIATIONS: Remediation[] = [
  // — Identity: reset / lock / unlock —
  {
    slug: 'ms365-force-password-reset',
    provider: 'ms365',
    action_type: 'force_password_reset',
    title: 'Force password reset on next sign-in',
    summary: 'Require the user to set a new password when they next sign in.',
    why: "If a password may have leaked or been shared, force the user to pick a new one before the next session.",
    category: 'identity',
    risk: 'medium',
    reversible: false,
    requiresConfirmation: 'confirm',
    estimatedSeconds: 8,
    successRate: 99,
    target: 'user',
    requiredPermissions: ['User.ReadWrite.All'],
    previewLines: [
      'Flag the account to require a new password',
      'The current password stops working at their next sign-in',
      'Existing sessions stay active until you also revoke them',
    ],
  },
  {
    slug: 'ms365-revoke-sessions',
    provider: 'ms365',
    action_type: 'revoke_sessions',
    title: 'Revoke all active Microsoft sessions',
    summary: 'Sign the user out of every device and refresh token.',
    why: 'Kicks the attacker (and the user) out of Teams, Outlook, browser tabs — anywhere their tokens are cached.',
    category: 'session_cloud',
    risk: 'medium',
    reversible: false,
    requiresConfirmation: 'confirm',
    estimatedSeconds: 6,
    successRate: 99,
    target: 'user',
    requiredPermissions: ['User.RevokeSessions.All', 'User.ReadWrite.All'],
    previewLines: [
      'Invalidate every issued refresh token for the account',
      'Sign the user out of Teams, Outlook and browser sessions',
      'They will need to sign in again — with MFA if enforced',
    ],
  },
  {
    slug: 'ms365-block-signin',
    provider: 'ms365',
    action_type: 'block_signin',
    title: 'Block the user from signing in',
    summary: 'Disable the account without deleting it.',
    why: 'Freezes the account instantly while you investigate. Fully reversible.',
    category: 'identity',
    risk: 'high',
    reversible: true,
    reverseSlug: 'ms365-unblock-signin',
    requiresConfirmation: 'typed_name',
    estimatedSeconds: 5,
    successRate: 99,
    target: 'user',
    requiredPermissions: ['User.ReadWrite.All'],
    previewLines: [
      'Set accountEnabled = false in Entra ID',
      'Every new sign-in attempt is denied immediately',
      'Existing tokens keep working until you revoke sessions',
    ],
  },
  {
    slug: 'ms365-unblock-signin',
    provider: 'ms365',
    action_type: 'unblock_signin',
    title: 'Re-enable the user',
    summary: 'Restore sign-in access for a previously blocked account.',
    why: "Once you've confirmed the account is safe, re-enable it and let the user back in.",
    category: 'identity',
    risk: 'medium',
    reversible: true,
    reverseSlug: 'ms365-block-signin',
    requiresConfirmation: 'confirm',
    estimatedSeconds: 5,
    target: 'user',
    requiredPermissions: ['User.ReadWrite.All'],
    previewLines: [
      'Set accountEnabled = true in Entra ID',
      'The user can sign in again immediately',
    ],
  },
  {
    slug: 'ms365-disable-user',
    provider: 'ms365',
    action_type: 'disable_user',
    title: 'Disable the user account entirely',
    summary: 'Same as block sign-in, plus revoke every active session.',
    why: 'The nuclear option for a compromised account: block sign-in AND kick every existing session in one step.',
    category: 'identity',
    risk: 'high',
    reversible: true,
    reverseSlug: 'ms365-unblock-signin',
    requiresConfirmation: 'typed_name',
    estimatedSeconds: 10,
    successRate: 99,
    target: 'user',
    requiredPermissions: ['User.ReadWrite.All', 'User.RevokeSessions.All'],
    previewLines: [
      'Block sign-in for the account',
      'Revoke every active refresh token',
      "Result: no way in until you re-enable them",
    ],
  },
  {
    slug: 'ms365-reset-mfa-methods',
    provider: 'ms365',
    action_type: 'reset_mfa_methods',
    title: 'Reset the user\u2019s MFA registrations',
    summary: 'Delete every registered MFA method so the user must re-enrol.',
    why: 'If an attacker registered their own phone or authenticator app, this wipes those methods.',
    category: 'identity',
    risk: 'high',
    reversible: false,
    requiresConfirmation: 'typed_name',
    estimatedSeconds: 12,
    target: 'user',
    requiredPermissions: ['UserAuthenticationMethod.ReadWrite.All'],
    previewLines: [
      'Enumerate every phone, authenticator and FIDO key on the account',
      'Delete each one via Graph',
      'The user must re-register MFA at next sign-in',
    ],
  },
  {
    slug: 'ms365-dismiss-risky-user',
    provider: 'ms365',
    action_type: 'dismiss_risky_user',
    title: 'Dismiss the risky-user flag',
    summary: 'Clear the Entra ID Protection risk state for the user.',
    why: "Once you've verified the risky sign-in was legitimate (or fully contained), clear the flag so Conditional Access stops challenging them.",
    category: 'identity',
    risk: 'low',
    reversible: false,
    requiresConfirmation: 'confirm',
    estimatedSeconds: 6,
    target: 'user',
    requiredPermissions: ['IdentityRiskyUser.ReadWrite.All'],
    previewLines: [
      'Call /identityProtection/riskyUsers/dismiss',
      'Ray records the dismissal in your audit trail',
    ],
  },
];
