-- Add missing columns to network_scans table for SafeNet API compatibility
ALTER TABLE public.network_scans 
ADD COLUMN IF NOT EXISTS network_ranges TEXT[] NOT NULL DEFAULT '{}',
ADD COLUMN IF NOT EXISTS scan_duration INTEGER NOT NULL DEFAULT 0,
ADD COLUMN IF NOT EXISTS scanned_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
ADD COLUMN IF NOT EXISTS hostname TEXT NOT NULL DEFAULT '',
ADD COLUMN IF NOT EXISTS results JSONB NOT NULL DEFAULT '{}',
ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now();