-- Add missing columns to custom_gpts table for comprehensive personalization
ALTER TABLE public.custom_gpts ADD COLUMN IF NOT EXISTS primary_color TEXT DEFAULT '#3b82f6';
ALTER TABLE public.custom_gpts ADD COLUMN IF NOT EXISTS secondary_color TEXT DEFAULT '#3b82f6';
ALTER TABLE public.custom_gpts ADD COLUMN IF NOT EXISTS background_color TEXT DEFAULT '#ffffff';
ALTER TABLE public.custom_gpts ADD COLUMN IF NOT EXISTS background_type TEXT DEFAULT 'color';
ALTER TABLE public.custom_gpts ADD COLUMN IF NOT EXISTS language TEXT DEFAULT 'english';
ALTER TABLE public.custom_gpts ADD COLUMN IF NOT EXISTS placeholder_prompt TEXT DEFAULT 'How can I help you today?';
ALTER TABLE public.custom_gpts ADD COLUMN IF NOT EXISTS loading_indicator TEXT DEFAULT 'typing';
ALTER TABLE public.custom_gpts ADD COLUMN IF NOT EXISTS custom_loading_message TEXT;
ALTER TABLE public.custom_gpts ADD COLUMN IF NOT EXISTS starter_questions JSONB DEFAULT '[]'::jsonb;
ALTER TABLE public.custom_gpts ADD COLUMN IF NOT EXISTS starter_questions_header TEXT;
ALTER TABLE public.custom_gpts ADD COLUMN IF NOT EXISTS starter_questions_expand TEXT DEFAULT 'View More';
ALTER TABLE public.custom_gpts ADD COLUMN IF NOT EXISTS starter_questions_collapse TEXT DEFAULT 'View less';
ALTER TABLE public.custom_gpts ADD COLUMN IF NOT EXISTS custom_message_ending TEXT;
ALTER TABLE public.custom_gpts ADD COLUMN IF NOT EXISTS error_message TEXT;
ALTER TABLE public.custom_gpts ADD COLUMN IF NOT EXISTS conversation_duration TEXT DEFAULT '24hours';
ALTER TABLE public.custom_gpts ADD COLUMN IF NOT EXISTS unknown_message TEXT;
ALTER TABLE public.custom_gpts ADD COLUMN IF NOT EXISTS show_citations TEXT DEFAULT 'dont_display';
ALTER TABLE public.custom_gpts ADD COLUMN IF NOT EXISTS should_mention_sources BOOLEAN DEFAULT true;
ALTER TABLE public.custom_gpts ADD COLUMN IF NOT EXISTS agent_capability TEXT DEFAULT 'optimal';
ALTER TABLE public.custom_gpts ADD COLUMN IF NOT EXISTS generate_responses_from TEXT DEFAULT 'my_data_llm';
ALTER TABLE public.custom_gpts ADD COLUMN IF NOT EXISTS ai_model TEXT DEFAULT 'gpt-4o';
ALTER TABLE public.custom_gpts ADD COLUMN IF NOT EXISTS user_feedback BOOLEAN DEFAULT true;
ALTER TABLE public.custom_gpts ADD COLUMN IF NOT EXISTS conversation_sharing BOOLEAN DEFAULT true;
ALTER TABLE public.custom_gpts ADD COLUMN IF NOT EXISTS conversation_exporting BOOLEAN DEFAULT false;
ALTER TABLE public.custom_gpts ADD COLUMN IF NOT EXISTS remove_branding BOOLEAN DEFAULT false;
ALTER TABLE public.custom_gpts ADD COLUMN IF NOT EXISTS agent_title TEXT;
ALTER TABLE public.custom_gpts ADD COLUMN IF NOT EXISTS title_color TEXT DEFAULT '#000000';
ALTER TABLE public.custom_gpts ADD COLUMN IF NOT EXISTS spotlight_avatar BOOLEAN DEFAULT false;
ALTER TABLE public.custom_gpts ADD COLUMN IF NOT EXISTS user_avatar BOOLEAN DEFAULT false;
ALTER TABLE public.custom_gpts ADD COLUMN IF NOT EXISTS avatar_orientations TEXT DEFAULT 'agent_left_user_right';
ALTER TABLE public.custom_gpts ADD COLUMN IF NOT EXISTS terms_of_service TEXT;
ALTER TABLE public.custom_gpts ADD COLUMN IF NOT EXISTS affiliate_id TEXT;
ALTER TABLE public.custom_gpts ADD COLUMN IF NOT EXISTS anti_hallucination BOOLEAN DEFAULT true;
ALTER TABLE public.custom_gpts ADD COLUMN IF NOT EXISTS agent_visibility TEXT DEFAULT 'public';
ALTER TABLE public.custom_gpts ADD COLUMN IF NOT EXISTS recaptcha BOOLEAN DEFAULT false;
ALTER TABLE public.custom_gpts ADD COLUMN IF NOT EXISTS whitelisted_domains TEXT;
ALTER TABLE public.custom_gpts ADD COLUMN IF NOT EXISTS conversation_retention TEXT DEFAULT '12_months';