// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nsyobmjpdpvesjwdphlh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5zeW9ibWpwZHB2ZXNqd2RwaGxoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE1NjM3MjksImV4cCI6MjA2NzEzOTcyOX0.vkV_Xr2T28WA6kiOzcZ3LhzmbkozWNy8Lvx0b7GTgWI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

// Storage key for auth token
const AUTH_STORAGE_KEY = 'sb-nsyobmjpdpvesjwdphlh-auth-token';

// Helper to get the root domain for cookie sharing across subdomains
const getRootDomain = (): string => {
  const hostname = window.location.hostname;
  
  // Localhost - no domain sharing possible
  if (hostname === 'localhost' || hostname === '127.0.0.1') {
    return '';
  }
  
  // Handle preview/production domains
  const parts = hostname.split('.');
  if (parts.length >= 2) {
    // Return last two parts (e.g., "ultriumai.com" from "safesuite.ultriumai.com")
    // For lovable.app domains, return last two parts
    return '.' + parts.slice(-2).join('.');
  }
  
  return '';
};

// Check if we're on a subdomain (not the main domain)
const isSubdomain = (): boolean => {
  const hostname = window.location.hostname;
  if (hostname === 'localhost' || hostname === '127.0.0.1') return false;
  
  const parts = hostname.split('.');
  // Main domains: ultriumai.com (2 parts), ultriumai.lovable.app (3 parts but pattern specific)
  // Subdomains: safesuite.ultriumai.com (3 parts), id-preview--xxx.lovable.app
  return parts.length > 2 || hostname.includes('preview--');
};

// Cookie-based storage for cross-subdomain session sharing
const cookieStorage = {
  getItem: (key: string): string | null => {
    if (typeof document === 'undefined') return null;
    
    // On subdomains, prioritize cookie over localStorage
    // because localStorage is per-origin and won't have the session after redirect
    const onSubdomain = isSubdomain();
    
    // Try cookie first on subdomains (cross-domain session sharing)
    if (onSubdomain) {
      const cookieValue = getCookieValue(key);
      if (cookieValue) {
        // Sync to localStorage for future reads
        try {
          localStorage.setItem(key, cookieValue);
        } catch (e) {
          // localStorage might be unavailable
        }
        return cookieValue;
      }
    }
    
    // Try localStorage (faster for same-origin)
    try {
      const localValue = localStorage.getItem(key);
      if (localValue) return localValue;
    } catch (e) {
      // localStorage might be unavailable
    }
    
    // Fallback to cookie for main domain
    return getCookieValue(key);
  },
  
  setItem: (key: string, value: string): void => {
    if (typeof document === 'undefined') return;
    
    // Always store in localStorage for fast access
    try {
      localStorage.setItem(key, value);
    } catch (e) {
      // localStorage might be unavailable
    }
    
    // Also store in cookie for cross-subdomain sharing
    const rootDomain = getRootDomain();
    const expires = new Date();
    expires.setTime(expires.getTime() + 365 * 24 * 60 * 60 * 1000); // 1 year
    
    let cookieString = `${key}=${encodeURIComponent(value)}; expires=${expires.toUTCString()}; path=/; SameSite=Lax; Secure`;
    if (rootDomain) {
      cookieString += `; domain=${rootDomain}`;
    }
    
    document.cookie = cookieString;
  },
  
  removeItem: (key: string): void => {
    if (typeof document === 'undefined') return;
    
    // Remove from localStorage
    try {
      localStorage.removeItem(key);
    } catch (e) {
      // localStorage might be unavailable
    }
    
    // Remove from cookie
    const rootDomain = getRootDomain();
    let cookieString = `${key}=; expires=Thu, 01 Jan 1970 00:00:00 GMT; path=/`;
    if (rootDomain) {
      cookieString += `; domain=${rootDomain}`;
    }
    document.cookie = cookieString;
  },
};

// Helper function to get cookie value
function getCookieValue(key: string): string | null {
  const cookies = document.cookie.split(';');
  for (const cookie of cookies) {
    const [cookieName, ...cookieValueParts] = cookie.trim().split('=');
    if (cookieName === key) {
      const cookieValue = cookieValueParts.join('='); // Handle values with = in them
      try {
        return decodeURIComponent(cookieValue);
      } catch {
        return cookieValue;
      }
    }
  }
  return null;
}

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: typeof window !== 'undefined' ? cookieStorage : undefined,
    storageKey: AUTH_STORAGE_KEY,
    persistSession: true,
    autoRefreshToken: true,
    detectSessionInUrl: true,
  }
});