// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nsyobmjpdpvesjwdphlh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5zeW9ibWpwZHB2ZXNqd2RwaGxoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE1NjM3MjksImV4cCI6MjA2NzEzOTcyOX0.vkV_Xr2T28WA6kiOzcZ3LhzmbkozWNy8Lvx0b7GTgWI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

// Determine the storage key prefix based on subdomain for session isolation
const getStorageKeyPrefix = () => {
  const hostname = typeof window !== 'undefined' ? window.location.hostname : '';
  if (hostname.startsWith('safesuite.')) {
    return 'sb-safesuite-auth-token';
  }
  return 'sb-nsyobmjpdpvesjwdphlh-auth-token';
};

// Custom storage that uses consistent keys across page refreshes
const customStorage = {
  getItem: (key: string) => {
    const storageKey = key.includes('auth-token') ? getStorageKeyPrefix() : key;
    return localStorage.getItem(storageKey);
  },
  setItem: (key: string, value: string) => {
    const storageKey = key.includes('auth-token') ? getStorageKeyPrefix() : key;
    localStorage.setItem(storageKey, value);
  },
  removeItem: (key: string) => {
    const storageKey = key.includes('auth-token') ? getStorageKeyPrefix() : key;
    localStorage.removeItem(storageKey);
  },
};

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: customStorage,
    persistSession: true,
    autoRefreshToken: true,
    detectSessionInUrl: true,
    flowType: 'pkce',
  }
});