import { serve } from "https://deno.land/std@0.168.0/http/server.ts";

const corsHeaders = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Headers": "authorization, x-client-info, apikey, content-type, x-supabase-client-platform, x-supabase-client-platform-version, x-supabase-client-runtime, x-supabase-client-runtime-version",
};

interface FileInput {
  path: string;
  content: string;
}

serve(async (req) => {
  if (req.method === "OPTIONS") return new Response(null, { headers: corsHeaders });

  try {
    const { token, repoName, isPrivate, files, description } = await req.json();

    if (!token || !repoName || !files?.length) {
      return new Response(JSON.stringify({ error: "Missing required fields: token, repoName, files" }), {
        status: 400,
        headers: { ...corsHeaders, "Content-Type": "application/json" },
      });
    }

    const headers = {
      Authorization: `Bearer ${token}`,
      Accept: "application/vnd.github+json",
      "Content-Type": "application/json",
      "X-GitHub-Api-Version": "2022-11-28",
    };

    // 1. Create repository
    const createRepoResp = await fetch("https://api.github.com/user/repos", {
      method: "POST",
      headers,
      body: JSON.stringify({
        name: repoName,
        description: description || `Generated by AI App Builder`,
        private: isPrivate ?? true,
        auto_init: true, // creates default branch with README
      }),
    });

    if (!createRepoResp.ok) {
      const err = await createRepoResp.json();
      if (err.errors?.[0]?.message?.includes("name already exists")) {
        return new Response(JSON.stringify({ error: `Repository '${repoName}' already exists. Choose a different name.` }), {
          status: 409,
          headers: { ...corsHeaders, "Content-Type": "application/json" },
        });
      }
      console.error("Create repo error:", err);
      return new Response(JSON.stringify({ error: err.message || "Failed to create repository" }), {
        status: createRepoResp.status,
        headers: { ...corsHeaders, "Content-Type": "application/json" },
      });
    }

    const repo = await createRepoResp.json();
    const owner = repo.owner.login;

    // 2. Get default branch SHA
    // Small delay to let GitHub initialize the repo
    await new Promise(r => setTimeout(r, 1500));

    const refResp = await fetch(`https://api.github.com/repos/${owner}/${repoName}/git/ref/heads/main`, {
      headers,
    });

    if (!refResp.ok) {
      const refErr = await refResp.text();
      console.error("Get ref error:", refErr);
      return new Response(JSON.stringify({ error: "Failed to get branch reference", repoUrl: repo.html_url }), {
        status: 500,
        headers: { ...corsHeaders, "Content-Type": "application/json" },
      });
    }

    const refData = await refResp.json();
    const baseSha = refData.object.sha;

    // 3. Create blobs for each file
    const treeItems = [];
    for (const file of files as FileInput[]) {
      const blobResp = await fetch(`https://api.github.com/repos/${owner}/${repoName}/git/blobs`, {
        method: "POST",
        headers,
        body: JSON.stringify({
          content: file.content,
          encoding: "utf-8",
        }),
      });

      if (!blobResp.ok) {
        console.error("Blob error for", file.path, await blobResp.text());
        continue;
      }

      const blob = await blobResp.json();
      treeItems.push({
        path: file.path,
        mode: "100644",
        type: "blob",
        sha: blob.sha,
      });
    }

    // 4. Create tree
    const treeResp = await fetch(`https://api.github.com/repos/${owner}/${repoName}/git/trees`, {
      method: "POST",
      headers,
      body: JSON.stringify({
        base_tree: baseSha,
        tree: treeItems,
      }),
    });

    if (!treeResp.ok) {
      console.error("Tree error:", await treeResp.text());
      return new Response(JSON.stringify({ error: "Failed to create file tree", repoUrl: repo.html_url }), {
        status: 500,
        headers: { ...corsHeaders, "Content-Type": "application/json" },
      });
    }

    const tree = await treeResp.json();

    // 5. Create commit
    const commitResp = await fetch(`https://api.github.com/repos/${owner}/${repoName}/git/commits`, {
      method: "POST",
      headers,
      body: JSON.stringify({
        message: "Initial commit from AI App Builder",
        tree: tree.sha,
        parents: [baseSha],
      }),
    });

    if (!commitResp.ok) {
      console.error("Commit error:", await commitResp.text());
      return new Response(JSON.stringify({ error: "Failed to create commit", repoUrl: repo.html_url }), {
        status: 500,
        headers: { ...corsHeaders, "Content-Type": "application/json" },
      });
    }

    const commit = await commitResp.json();

    // 6. Update branch reference
    const updateRefResp = await fetch(`https://api.github.com/repos/${owner}/${repoName}/git/refs/heads/main`, {
      method: "PATCH",
      headers,
      body: JSON.stringify({ sha: commit.sha }),
    });

    if (!updateRefResp.ok) {
      console.error("Update ref error:", await updateRefResp.text());
    }

    return new Response(JSON.stringify({
      success: true,
      repoUrl: repo.html_url,
      filesCount: treeItems.length,
    }), {
      headers: { ...corsHeaders, "Content-Type": "application/json" },
    });

  } catch (e) {
    console.error("github-push error:", e);
    return new Response(JSON.stringify({ error: e instanceof Error ? e.message : "Unknown error" }), {
      status: 500,
      headers: { ...corsHeaders, "Content-Type": "application/json" },
    });
  }
});
